### ISSUE TITLE
Character missing name

### ISSUE THREAD

**Issue by Killmatronix** [ThePinkPanzer/Godherja-Github-Version#105]
https://i.imgur.com/P6uQs48.png
https://i.imgur.com/Y2NQdDR.png
Just has the house name

**Comment by Killmatronix** [comment]
https://i.imgur.com/Y2NQdDR.png

**Comment by Killmatronix** [comment]
https://i.imgur.com/Y2NQdDR.png

**Comment by ScionEol** [comment]
Already Fixed as of Patch 0.2.6.03
