### ISSUE TITLE
Tathtalite head of faith title shown in other Wardenite faith screens

### ISSUE THREAD

**Issue by Killmatronix** [ThePinkPanzer/Godherja-Github-Version#119]
https://i.imgur.com/Zy4AH2H.jpg
Tathtalite head of faith title, Mumarat, shown as temporal and shown to be owned by Adabyn.

https://i.imgur.com/JjLYsUH.png
Harthahi'a has no head of faith and still shows the Mumaramat. Same will be true for Ruidari'a.
Ruidari'a
https://i.imgur.com/k19qn1O.png

**Comment by ThatOneGuy42** [comment]
This is accurate and how it should look as The Mamur is the Mamur for each of those wardenite faiths and that only changes if new Mamuramats are formed(such as Western or Eastern, etc.)
