### ISSUE TITLE
Typos in bestiary - Shahmaran

### ISSUE THREAD

**Issue by eskoaaa** [ThePinkPanzer/Godherja-Github-Version#12]
![typo4](https://user-images.githubusercontent.com/100095885/154865725-28df3218-c3dd-4663-bc39-d367026b2f37.PNG)

- Long-extinct
- ps. Dragon capitalized on one occasion but uncapitalized on another

**Comment by ThePinkPanzer** [comment]
See #11 and #10

**Comment by ThePinkPanzer** [comment]
Fixed in 0.2.5.2
