### ISSUE TITLE
Call Hunt eventline just doesn't continue past "Let's begin" in whatever region Barencuir is in

### ISSUE THREAD

**Issue by Killmatronix** [ThePinkPanzer/Godherja-Github-Version#126]
https://i.imgur.com/8kpuvJm.jpg

Unsure of what to screenshot, but a dialogue option's also missing. Try doing it as the starting count of Barencuir.

**Comment by Killmatronix** [comment]
https://i.imgur.com/1jpjEnz.jpg

This one

**Comment by ThatOneGuy42** [comment]
fixed in current release
