### ISSUE TITLE
Various title issues relating to Uniting the empire and Restoring aversarian governates

### ISSUE THREAD

**Issue by kuromeolev** [ThePinkPanzer/Godherja-Github-Version#13]
Issue #1: Uniting the empire after initially forming the northern or southern empire (semi-empires) does not transfer over the kingdom-rank versions of the former governates to the de jure united aversaria, it leaves them as part of the semi-empire de jure title. This can additionaly result in Aversaria itself having no de jure land under it in case the original empire-rank governates were completely destroyed

Issue #2 (potentially intended): if the original empire-rank governate titles were completely destroyed, they will not be restored by the decision to restore de jure aversarian hierarchies. However, in case of partial loss of de jure territory they are fully restored to their original scope

Issue #3 : The decisions to restore de jure aversarian hierarchies becomes available after the empire-rank governates are turned into kingdom titles by either of the empire-forming/uniting decisions, and will result in the total (or in some cases, partial) destruction of said kingdom titles de jure territory
![image](https://user-images.githubusercontent.com/100096625/154865745-28a859b7-0669-4e7d-9834-7bc98b5e4e7b.png)
(example of what happened after taking the Restore Opakhasia decision after it had been turned into a kingdom, kingdom titles mapmode. Note the rump Opakhasia title in the red wastes and southern islands)

**Comment by FedorBozic** [comment]
After a fair bit of refactoring, I think that all three of these should now be solved. There's still probably some weirdness when it comes to this stuff, but these specific bugs should be done for.
