### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by VammTA** [ThePinkPanzer/Godherja-Github-Version#133]
As it is said in the title the mod crash on startup after couple of seconds on the loading screen. Godherja is the sole mod I'm using and I believe other people encountered this issue as I've roamed through reddit to find some solution, only to encounter posts with no relevant solutions.

**Comment by Netgearghost** [comment]
Without further information, this can't be replicated. If you continue to have issues please ping Netgear in the discord.
