### ISSUE TITLE
Message about "Ruler change Faith" keep repeating

### ISSUE THREAD

**Issue by DkHyacinth** [ThePinkPanzer/Godherja-Github-Version#134]
One of my character's fellow vassal changed his faith to Omitilos Aagiokratia, and the information bar keep repeating this message.
I met this bug before but at that time the gameplay was nearly at the end so I didn't care about it, I cannot remember which faith that character change to now but probably not Omitilos Aagiokratia

**Comment by FedorBozic** [comment]
Duplicate of
https://github.com/ThePinkPanzer/Godherja-Github-Version/issues/18
