### ISSUE TITLE
Malcois Aversarians naked

### ISSUE THREAD

**Issue by KaiserSolarius** [ThePinkPanzer/Godherja-Github-Version#136]
A lot of characters of the Malcois region seems to be naked and/or bald, and even if the no nudity rule is enabled. It looks like it only concerns characters of central and south aversarian cultures.

![Screenshot_851](https://user-images.githubusercontent.com/59295778/161247343-b848f707-6e28-4c21-a5ec-9c67d8066afa.jpg)

**Comment by FedorBozic** [comment]
Fixed
