### ISSUE TITLE
Duchy of Kamo incorrectly included as De Jure part of the Tower Isle Kingdom

### ISSUE THREAD

**Issue by ScionEol** [ThePinkPanzer/Godherja-Github-Version#138]
These isles west of chevalie are (incorrectly, I think) designated as de jure part of Kerkonia, the Tower Isle kingdom. In my current game, it also led to Cenware to declare war on Benouet, as he occupies part of these Islands.
![bug](https://user-images.githubusercontent.com/102801476/161250094-1cf092d0-bb82-4734-b1e2-b6c5eac053b6.png)

**Comment by ThatOneGuy42** [comment]
fixed on next patch
