### ISSUE TITLE
Localization missing from multiple titles

### ISSUE THREAD

**Issue by eskoaaa** [ThePinkPanzer/Godherja-Github-Version#14]
![typo5](https://user-images.githubusercontent.com/100095885/154865811-2ce08cc7-0414-4b73-b8ff-0097ea8dbb36.PNG)
![typo5 5](https://user-images.githubusercontent.com/100095885/154865813-8be8875f-bdd3-480d-8105-e312c2b567b5.PNG)

**Comment by Netgearghost** [comment]
Localisation added for all b_ prefixes
