### ISSUE TITLE
Forternons in a few places where they should not have been + Issue with metropolis in a kothex of Astassus

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#142]
![Zrzut ekranu (154)](https://user-images.githubusercontent.com/101152217/161274367-f890f5e0-ccd8-47a5-8d59-cecfabb08bd6.png)
![Zrzut ekranu (155)](https://user-images.githubusercontent.com/101152217/161274403-7e032e83-3ac9-4be4-804f-24a05f9b3377.png)
![Zrzut ekranu (156)](https://user-images.githubusercontent.com/101152217/161274423-ce9481ff-d96f-4db3-8231-4ae559fd7e1f.png)
![Zrzut ekranu (157)](https://user-images.githubusercontent.com/101152217/161274433-31dad1e9-8da2-4d2a-8c1f-aec3c5016e49.png)

**Comment by FatLeek** [comment]
Of course this issue is a castle instead of district

**Comment by ThatOneGuy42** [comment]
fixed in next patch
