### ISSUE TITLE
Learn Magic Scheme Freezes and after completions doesn't delete itself

### ISSUE THREAD

**Issue by Sofistico** [ThePinkPanzer/Godherja-Github-Version#146]
When you finish the scheme and the completion event fires, the game doesn't remove the scheme from the list and remain indefinitely in the schemes window, taking space from the other schemes.
![image](https://user-images.githubusercontent.com/59299346/161340645-b439f05d-6cc5-4610-9bbf-940fb935f62e.png)

**Comment by Bommelom1** [comment]
Forgot to add end_scheme to the success effect of the schemes as well as the failure effect, should be fixed in the next version.
