### ISSUE TITLE
Mazunic culture starts with no innovations

### ISSUE THREAD

**Issue by Larko01** [ThePinkPanzer/Godherja-Github-Version#149]
Mazunic culture starts in tribal era without any innovations
![image](https://user-images.githubusercontent.com/102861631/161385239-c61c29a9-5cde-4cbd-aee0-31d9fa1afe12.png)

**Comment by Bommelom1** [comment]
Happened because we accidentally named their innovations file heritage_dezhun instead of heritage_dezhunic, should be fixed next version
