### ISSUE TITLE
Typo in religious text

### ISSUE THREAD

**Issue by eskoaaa** [ThePinkPanzer/Godherja-Github-Version#15]
![typo6](https://user-images.githubusercontent.com/100095885/154865874-b739fb24-dcd9-4489-a76e-cbfe486abfdb.PNG)

- chief-god(?)
- ps "...many foreign insults, their holy men..." could maybe use a "but" or something

**Comment by ThePinkPanzer** [comment]
What is the typo here?

**Comment by FedorBozic** [comment]
Fixed the awkward phrasing
