### ISSUE TITLE
Fortenorns in Aironoi 

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#150]
In these two counties here
![Zrzut ekranu (161)](https://user-images.githubusercontent.com/101152217/161385824-20857cd0-3e10-4285-86fe-922cac5c347c.png)
![Zrzut ekranu (162)](https://user-images.githubusercontent.com/101152217/161385825-0e6ad175-793b-4fac-8aff-4ee61981b1f9.png)
e

**Comment by FedorBozic** [comment]
Fixed
