### ISSUE TITLE
Issues with Huegodoc kingdoms and relocation of their holy sites

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#162]
First, founding of any Huegodoc kingdom, like Heugordica, Rithogedica etc. does not give a title and cultural tradition
![Zrzut ekranu (169)](https://user-images.githubusercontent.com/101152217/161447726-ba098463-2298-4dab-8d4f-1d0652d45407.png)
. 
Also, one can "establish" all of these kingdoms at once without restrictions, getting whooping amounts of development (This is my capital)
![Zrzut ekranu (168)](https://user-images.githubusercontent.com/101152217/161447803-f7032413-e250-448c-9963-44cea7e2cb08.png)
.
And, if Huegodoc character that is fulfilling requirements holds barony in any region, he can relocate, and potentially create new holy sites of Apti faith, in this case quadrupling the amount of holy site (In this case, Opakhasian Huegodoc AI also founded holy sites in Opakhasia)
![Zrzut ekranu (167)](https://user-images.githubusercontent.com/101152217/161447949-35d3faa4-508e-48be-9c9e-b3ee99bed3d4.png)
s

**Comment by FatLeek** [comment]
Better check also Salacad relocation of holy sites, there could be similar issue

**Comment by FatLeek** [comment]
Also, the decision about moving holy sites to Etepezea is weirdly called, something like "Move Manasteries to the Etepezean Sea", better check other namings of these decisions

**Comment by forkis** [comment]
the kingdom titles were yeeted due to a merge issue,they've been readded. Special is-valid lines added to prevent the AI from taking the holy site decisions if someone else has already used one.
