### ISSUE TITLE
Capital county of the Podrocrech (Duchy) of Termesivy has city as it's main holding, effectively making sjalvolki kingdom here a republic every single time

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#163]
![Zrzut ekranu (170)](https://user-images.githubusercontent.com/101152217/161575951-6b1d01d1-7225-43cc-bad7-ca792273fcee.png)
![Zrzut ekranu (171)](https://user-images.githubusercontent.com/101152217/161576230-551ec565-24f7-44b4-be5a-e8f0a392b6a9.png)

**Comment by FatLeek** [comment]
Most surprising is a fact that republic in the screenshot does not use cliques and influence mechanics

**Comment by Notanoctopus8** [comment]
On a related note, a lot of random duchies and counties end up being theocracies and republics for this reason. Not sure if it is intended behaviour or not. It can lead to the player ending up as a different government without realising it if they join the migration.
