### ISSUE TITLE
New Imperrech vassals given default faith and culture

### ISSUE THREAD

**Issue by Psammetichos** [ThePinkPanzer/Godherja-Github-Version#17]
![image](https://user-images.githubusercontent.com/100099322/154868219-027700c7-32c8-40d5-a3d9-2b6e2f319d59.png)

New vassals generated for the Imperrech during its conquests (and of course their counties) are being assigned the Alau Koevec faith and Nizhbata culture. These are just the first faith and culture available in the files, i.e. the system uses them when it doesn't know what it should do. As far as I can tell Sjalvolki vassals appear just fine, but no non-Sjalvolki are being properly generated.

**Comment by ScionEol** [comment]
Already fixed as of Patch 0.2.6.03
