### ISSUE TITLE
Large Aelvar Shard no loc

### ISSUE THREAD

**Issue by Cirkasius** [ThePinkPanzer/Godherja-Github-Version#172]
![20220406013132_1](https://user-images.githubusercontent.com/100110550/161902476-62584264-50f5-4dc2-82ec-cb4a6ad220a5.jpg)
![20220406013134_1](https://user-images.githubusercontent.com/100110550/161902480-20304966-a604-414a-870b-bc4a06cbffde.jpg)

**Comment by Cirkasius** [comment]
Same goes for Huge Aervalr shards

**Comment by Netgearghost** [comment]
Fixed
