### ISSUE TITLE
Coa Titular and Dynastic editor issue 

### ISSUE THREAD

**Issue by Kasparian1776** [ThePinkPanzer/Godherja-Github-Version#180]
The sliders for adjusting the emblems are missing and only the rotation of the emblems is available with shoddy UI.
![GH issue](https://user-images.githubusercontent.com/103205523/162245287-7cb4aa91-4c86-4875-98dc-1783099e189d.png)

**Comment by FedorBozic** [comment]
![image](https://user-images.githubusercontent.com/6509794/163587005-3788bff5-6725-46ba-984a-2bf12a87bc54.png)
I cannot confirm this issue. On my end, it looks completely normal. Are you using any other mods?
