### ISSUE TITLE
Capital of Kargagos county is inaccessible 

### ISSUE THREAD

**Issue by F00tMaNatArMs** [ThePinkPanzer/Godherja-Github-Version#181]
![image](https://user-images.githubusercontent.com/103208921/162255114-056c628f-04eb-4739-9e06-c0d2e2f24410.png)
![image](https://user-images.githubusercontent.com/103208921/162256020-9af64c65-3462-4ae6-bc56-9d6c0cefcee5.png)

The county of Kargagos seems to be partly in the mountain and therefore cannot be clicked on, specifically barony of Keos

**Comment by Netgearghost** [comment]
Fixed
