### ISSUE TITLE
"Declare Yourself Malaak" bug

### ISSUE THREAD

**Issue by GoodGirlZoria** [ThePinkPanzer/Godherja-Github-Version#183]
It's possible to take the decision "Declare Yourself Malaak", even if you have taken it before
![MalaakBug](https://user-images.githubusercontent.com/103272929/162477173-07c6653a-0d5b-43dd-9ca6-33998500f011.png)

**Comment by ScionEol** [comment]
Already fixed as of Patch 0.2.6.03
