### ISSUE TITLE
Bookmark for Mad Dog Ulfirx links to wrong character 

### ISSUE THREAD

**Issue by Notanoctopus8** [ThePinkPanzer/Godherja-Github-Version#186]
When you use the suggested character bookmarks, 'Mad Dog' Ulfirx will start the game as the wrong character. 
The opening message for Ulfirx will play, but you will start as Chieftan Eudoxias of Kathaeras, a Sea Cultist Central Aversarian Islander.
If you start by choosing any ruler, and manually choose Ulfirx, then you do not get the opening message, but you do start as the correct character.

**Comment by Archduke476** [comment]
Fixed on the dev build
