### ISSUE TITLE
Misspelling in Griffon Attack event "Narrowing Down the Search"

### ISSUE THREAD

**Issue by Watersidebullet** [ThePinkPanzer/Godherja-Github-Version#187]
There's a mispelling between the two paragraphs for the Griffon Hunt event "Narrowing Down the Search"

![image](https://user-images.githubusercontent.com/103294680/162639673-ead82a3b-82bd-42ac-a1e8-08a48f07691c.png)

**Comment by FedorBozic** [comment]
Fixed
