### ISSUE TITLE
Perigcos is a republic

### ISSUE THREAD

**Issue by Cirkasius** [ThePinkPanzer/Godherja-Github-Version#189]
![20220412193725_1](https://user-images.githubusercontent.com/100110550/163071561-a46145c7-2669-4582-a2d6-f3ad1239418e.jpg)

**Comment by FedorBozic** [comment]
I cannot confirm this issue on my end (Pergicos is feudal for me), which means that it's either been solved by accident, your descriptor is messed up or you're using other mods.
