### ISSUE TITLE
Harthah can't use the Reconquest of Sarradon cassus belli

### ISSUE THREAD

**Issue by transfemgodtamer** [ThePinkPanzer/Godherja-Github-Version#19]
harthah ibn sarradon cannot use the reconquest of sarradon cassus belli. his starting war is even invalidated due to this, and he cannot declare any reconquest wars after that. what was previously a proper "reconquest" war CB is now completely blank, and cannot be declared. i tried this with all other mods disabled, this is clearly present

**Comment by ThePinkPanzer** [comment]
#8
