### ISSUE TITLE
Wasteland Aladdin

### ISSUE THREAD

**Issue by hteven** [ThePinkPanzer/Godherja-Github-Version#190]
Using the Aladdin reference event in the hold court event, it is possible to get a man claiming to be king of the Wasteland. If you agree to marry your daughter to him, you can get a no religion no culture husband, meaning that if you play as the daughter you can convert to the no religion
![20220416174134_1](https://user-images.githubusercontent.com/102885864/163692269-3aa25df3-3806-47a8-b6a9-aa97a134877e.jpg)
![20220416174120_1](https://user-images.githubusercontent.com/102885864/163692276-36bd8087-6209-42bc-8943-36c4301c5e44.jpg)
![20220416111609_1](https://user-images.githubusercontent.com/102885864/163692289-e6fc7007-7a08-4a9e-a111-13a49f2bd577.jpg)

**Comment by hteven** [comment]
Also here is Prince Wasteland Wasteland in all his glory
![20220416175007_1](https://user-images.githubusercontent.com/102885864/163692392-dc033329-db0a-429f-892f-d840fc908cd7.jpg)

**Comment by FedorBozic** [comment]
Fixed
