### ISSUE TITLE
The Feast dosnt work

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#193]
I start the in-game event - start feast. 
I am charged money, stress is reduced, as written in the description, then nothing happens.
In my palace opens feast activity, sitting guests - no events happen, as in the vanilla game. 
Half a year or so passes, feast closes, everyone goes home. 
The farewell event that "the guests left and increased attitude to you" does not happen.

I play in the Sarradon region and ran into this problem.
The version of the game is the latest. The game is started from the beginning .
PS: I don't use any mods other than GH.

![Screenshot_1](https://user-images.githubusercontent.com/86404525/164003145-387ca35b-fdfa-4395-9a4b-668c99ce3c31.jpg)

**Comment by Notanoctopus8** [comment]
This seems to be happening a lot now - occasionally it works as normal but 80-90% of the time it doesn't progress past the first popup window.
In my case it was as a Sjalvolki feudal and Pirate (at different times).
Lots of comments in the Discord seem to indicate it is a widespread issue.

**Comment by FedorBozic** [comment]
Fixed

**Comment by Dimka2010** [comment]
Please, can you put this files with fixes?

**Comment by Dimka2010** [comment]
work normal after update
