### ISSUE TITLE
missing structure bonus

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#194]
At 2nd upgrade stage level have +10 Supply Limit, in 3rd stage ugrade level = no.
![Screenshot_2](https://user-images.githubusercontent.com/86404525/164003932-748307a2-17b3-458e-9a49-9798ad9dcc80.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/86404525/164003935-7450e4b3-f2d6-430c-aa0b-c508f5aa367d.jpg)

**Comment by Netgearghost** [comment]
Added in the supply limit to the level 3 building
