### ISSUE TITLE
Extremely illogical purchase price for a falcon

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#195]
I decided to buy a falcon one day.
![falcon_10](https://user-images.githubusercontent.com/86404525/164044691-d2f32cd7-d376-4445-bc24-fda7ec3e14a5.jpg)

Running the solution. not shown the price, as in other solutions (you can see what I mean by the example of "start hunting" or "arrange a feast" solutions, where you can immediately see how much gold I would give for it).
![Screenshot_1](https://user-images.githubusercontent.com/86404525/164050261-dcd99f4d-93fe-4f72-a076-084a663cbca3.jpg)

Then they show the price - 500 gold pieces!
![Screenshot_10](https://user-images.githubusercontent.com/86404525/164045052-90ee3fb4-eb92-40fa-98bf-59567226f576.jpg)

Are you guys serious? Five hundred gold pieces?
That is a minimum of 2-3 generations of characters later will be available when the average income will be at least 10-20 coins per month from the average AI bots? Or even later?
Or will the player have to give up building a building for 100-200 coins, save up for 5-10 years to take advantage of the event after all? 

Okay. Spend 500 coins, and what do we see?
![Screenshot_11](https://user-images.githubusercontent.com/86404525/164045997-1f5ea576-0346-48df-aebc-7a6b4fcfb48f.jpg)![Screenshot_11]

Random decided to play with us.
30% vs. 60% that I wasted those 500 coins and threw them away? And I find out a couple of weeks later? I understand that it's done from save-load, I'm fine with it. And the interest rate. although the first time I ran this quest to train a falcon, without the second perk to hunt, then I had something like less than 10% success rate at all and I couldn't tame the falcon, in the end. 
500 coins... then failure... 
500 coins - now failure...
I think this event is too damn expensive!
An adequate price to run it is **15-50 coins at most.** Have a feast of 250 coins, as an example. And running a falcon = 500! Build a building 150 coins, or run a falcon for the price of three of those buildings :)
For buildings you are guaranteed to get something, and here guaranteed = nothing :) 
guys, change the price of launching a falcon. And the AI will be able to use it and the players.
The percentages don't need to be touched - random is random.

All this on the lands of Saradon. Maybe other lands have a discount, I do not know.

PS: Please give me a tip where I can change the price of this event to take advantage of it and test it out.
PPS: used translator.

**Comment by FedorBozic** [comment]
Implemented suggested changes and generally polished the falcon training decision
