### ISSUE TITLE
Fortenorns Still In Aironoi

### ISSUE THREAD

**Issue by PuffedWheatSquare** [ThePinkPanzer/Godherja-Github-Version#197]
![20220421235025_1](https://user-images.githubusercontent.com/104187960/164612516-fe0e19a1-3f44-40c0-8961-40a7d56dbe68.jpg)
![20220421235029_1](https://user-images.githubusercontent.com/104187960/164612524-e9104426-6dc5-4dc6-87cb-484b65ab1509.jpg)
This should be the latest patch of the mod. I don't know if this is a me issue or not.

**Comment by FedorBozic** [comment]
Already fixed in the dev build
