### ISSUE TITLE
Decision Not Appearing post migration

### ISSUE THREAD

**Issue by CountPuurple** [ThePinkPanzer/Godherja-Github-Version#20]
![20220221111114_1](https://user-images.githubusercontent.com/28975950/154887469-f16f6a3e-f042-44c8-bae5-cf276cc824a3.jpg)

The decision to reform Aversaria does not appear despite meeting the criteria

**Comment by FedorBozic** [comment]
Should be fixed now that governorates can be restored even after their destruction.
