### ISSUE TITLE
Missing structure bonus

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#208]
![Screenshot_4](https://user-images.githubusercontent.com/86404525/165477612-0744b8f0-d1d0-4876-b83d-79b74b64873d.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/86404525/165477618-986499d2-f3d0-4f7d-aa70-7da92f2a0e63.jpg)

**Comment by Netgearghost** [comment]
Fixed
