### ISSUE TITLE
In `common\religion\religions\` `gh_pagan_wasteland.txt` and `gh_wasteland.txt` are identical except one line.

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#21]
In 'common\religion\religions\' 'gh_pagan_wasteland.txt' and 'gh_wasteland.txt' are identical except one line: `holy_site = oraispol`
![image](https://user-images.githubusercontent.com/86840465/154890292-d794c535-de80-4f1f-8cef-5732603db780.png)

**Comment by ThePinkPanzer** [comment]
Duplicate file removed in 0.2.5.2
