### ISSUE TITLE
Dissapeared falcon Training after update in Mamuramat lands.

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#210]
https://github.com/ThePinkPanzer/Godherja-Github-Version/issues/195

i wrote here about Falcon Training .
After update wanted to taste this feature, but...
![Screenshot_6](https://user-images.githubusercontent.com/86404525/165482255-b76ee1a3-5938-4ad9-901f-af96ee4ba63c.jpg)
No Falcon training here.

its dissapeared everywhere? or only in Mamuramat lands?
I dont use the console so cannot look on another Land Rulers.

**Comment by FedorBozic** [comment]
In order to have access to that decision, your culture either needs to have the relevant tradition or you need to have the beasthunter perk.
