### ISSUE TITLE
Hunting event that is of mod (I presume) has issues

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#211]
![Zrzut ekranu (187)](https://user-images.githubusercontent.com/101152217/165556302-1a97807e-368b-4e5f-88a1-e0c0d7c80850.png)
No immediate effects from decisions and no name of the event were provided, second option also has "No Immediate effects" as the first one had

**Comment by ThatOneGuy42** [comment]
Fixed in next patch
