### ISSUE TITLE
Another Hunting event that is certainly of mod has issues

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#212]
![Zrzut ekranu (188)](https://user-images.githubusercontent.com/101152217/165557012-c89c666f-0be9-45b3-95f3-fdc57cee4c02.png)
First option is relatively good, except two 33% chances are giving the same amount of gold (15), and the second is just "No immediate effects"

**Comment by FatLeek** [comment]
You should prop review all new hunting events, they all have similar problems

**Comment by ThatOneGuy42** [comment]
Fixed in next patch
