### ISSUE TITLE
Vassals seem to randomly declare independence with no warning, event, or trigger

### ISSUE THREAD

**Issue by wvfish** [ThePinkPanzer/Godherja-Github-Version#215]
Playing as a decently large pirate empire. Over the course of the game, random vassals will rarely declare independence with no event notifying the player. This has become game-ruining; the image below shows what my empire was (in red) and the vassals that have declared independence over the past in-game year (in blue). Most of these were vassals of vassals, but not all. My guess as to what happened is that my daughter, who ruled most of the vassals, failed the pirate succession check (15 martial + level 3 fame), but she had held her kingdom for several decades and only just now fell apart. This also doesn't explain some of the other independences. If this is intentional, there really needs to be an event for when a vassal fails the pirate check, because it's extremely annoying to suddenly see half your empire gone for no discernable reason. I also have no clue how the vassal on Krehejad itself would have gained independence, as that was a direct vassal of me, and I had passed the pirate succession check many years earlier.

![image](https://user-images.githubusercontent.com/42823452/165683045-3c21a9a8-35b8-4922-8ce6-1c77b5ffb262.png)

**Comment by GundraburWeishaupt** [comment]
I changed the said succession event for me so that when vassals "lose their fleet", they are transferred to me (their liege). To me, it made perfect sense that even if individual captains lose trust in their boss, they still remain loyal to their boss's boss (their liege's liege), be it out of loyalty or fear. I'm leaving the code here for those who want to play pirates and don't want to keep taking back individual counties because of incompetent vassals. I haven't tested the code extensively, but haven't had any spontaneous secessions since.

      gh_pirate.0006 = {
	      type = character_event
	      title = gh_pirate.0006.t
	      desc = gh_pirate.0006.desc
      
	      theme = skull
	      left_portrait = {
		      character = root
		      animation = stress
	      }
	      immediate = {
		      if = { # if you are a vassal, your vassals will only be transfered to your liege
			      limit = { is_independent_ruler = root } 
				      every_vassal = {
					      every_held_title = {
						      limit = { NOT = {tier = tier_barony }}
						      save_scope_as = titles
						      set_county_faith = root.faith
						      root = {
							      add_unpressed_claim = scope:titles
						      }
					      }
					      create_title_and_vassal_change = { #shift vassals to your liege
						      type = granted
						      save_scope_as = change
						      add_claim_on_loss = yes
					      }
					      hidden_effect = {
						      change_liege = { liege = root.liege change = scope:change }
						      save_scope_as = truce_loc
					      }
					      resolve_title_and_vassal_change = scope:change
				      }		
		      }
		      else = { 
				      every_vassal = {
					      every_held_title = {
						      limit = { NOT = {tier = tier_barony }}
						      save_scope_as = titles
						      set_county_faith = root.faith
						      root = {
							      add_unpressed_claim = scope:titles
						      }
					      }
					      create_title_and_vassal_change = {
						      type = independency
						      save_scope_as = change
						      add_claim_on_loss = yes
					      }
					      hidden_effect = {
						      becomes_independent = { change = scope:change }
						      save_scope_as = truce_loc
					      }
					      resolve_title_and_vassal_change = scope:change
				      }
		      }
		      
	      }
      
	      option = {
		      name = gh_pirate.0006.a
	      }
      }
