### ISSUE TITLE
Island with no connections or adjacencies in Kashirya

### ISSUE THREAD

**Issue by wvfish** [ThePinkPanzer/Godherja-Github-Version#223]
![2022_05_05_2](https://user-images.githubusercontent.com/42823452/166871032-2900d20c-814c-4f77-8800-dd8808afd54f.png)
![2022_05_05_3](https://user-images.githubusercontent.com/42823452/166871044-586ac778-28bb-40a7-bb69-de92f01beb90.png)
This province in a lake in Kashirya is completely inaccessible. You cannot get troops in or out, and it is impossible to conquer or diplo-vassalize (they consider you a "distant realm" for a -500 accept modifier because they have no adjacencies to you or anyone)

**Comment by wvfish** [comment]
To add onto this, this island province in the Kasiryat cannot be accessed unless you have the ability to traverse rivers, which nobody in the region does.
![2022_05_05_4](https://user-images.githubusercontent.com/42823452/167034396-3b9884e5-34ba-465f-8296-b23b3bc33449.png)
![2022_05_05_5](https://user-images.githubusercontent.com/42823452/167034406-74d210f1-ded5-44c0-85c6-238920b1c10b.png)

**Comment by wvfish** [comment]
Might as well put this here as well: the Kasiryat in general can be a bit of a nightmare. To make what should be a very short journey (in blue), you have to take an absurd roundabout crossing including two ocean crossings (in red) because you can't cross the Kasiryat without river travel. Please either make it so that the Kasiryat is treated as ocean provinces so people can cross it with ships or give it a number of crossable straits
![image](https://user-images.githubusercontent.com/42823452/167067377-b1c407d0-b81d-4718-a931-4bcfe9bbd31a.png)

**Comment by Netgearghost** [comment]
Added in adj to access the inaccessible islands, and allowed a little bit easier pathing
