### ISSUE TITLE
Missing files causes crash on startup

### ISSUE THREAD

**Issue by VammTA** [ThePinkPanzer/Godherja-Github-Version#227]
Since the 1.5 update, I kept getting crashs on startup with this mod. I've recently checked the logs to see what was happening and it appears that I have missing files? I tried to reinstall the mod but to no avail. I still have missing files and the mod will just crash on the first loading screens when launching CK3.

**Comment by Netgearghost** [comment]
Are you on the latest version? If you are still having trouble please ping Netgear in the discord
