### ISSUE TITLE
Salacad holy sites and decision lack loc (LOCALISATION BUG)

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#23]
When creating a coalition of salacad holy sites, the decision itself lacks loc and 3 of their holysites have no space between them (Silvers Fathers peak).
![bug 2](https://user-images.githubusercontent.com/100115457/154902191-c9863542-2339-4757-baef-978099adcc9c.png)

**Comment by forkis** [comment]
Fixed as part of implementation of a rudimentary holy site migration decision set.
