### ISSUE TITLE
Mamuramat and Royal Court inside their religion

### ISSUE THREAD

**Issue by Dimka2010** [ThePinkPanzer/Godherja-Github-Version#233]
could you make an election in the Royal Court, as in this event? 
So that candidates can be seen and calmly click on their portraits to see their stats and law skills
![Screenshot_1](https://user-images.githubusercontent.com/86404525/168421169-b1c2edb7-062f-4770-9552-9d34f10874d1.jpg)

it's just that now it's just three lines (without portraits, as in the screenshot), where it's very difficult to catch each name, wait until it becomes static, hover the mouse, and watch the character. Then repeat the same with the next one until you find the best one and choose it.
![Screenshot_1](https://user-images.githubusercontent.com/86404525/168421574-319cee2d-9ab5-48cf-b826-02a6e0e19e17.jpg)

**Comment by FedorBozic** [comment]
Implemented
