### ISSUE TITLE
The Skull-Taker's helmet always disappearing when I play him (but not when I don't)

### ISSUE THREAD

**Issue by Zamarak500** [ThePinkPanzer/Godherja-Github-Version#235]
Gorassos "Skull-Taker" has this great helmet . One problem, it always disappears when I play him, replaced by a generic military Aversarian helmet. Strangely, it doesn't change when I am not playing him. Any reason what might cause this?

**Comment by ThatOneGuy42** [comment]
Gorassos' helmet is an equipable artifact rather than a piece of clothing. Artifacts are not equipped when you load in.
