### ISSUE TITLE
Battle Magi Helmet(s) not showing up in Barbershop.

### ISSUE THREAD

**Issue by SULFonicgolf** [ThePinkPanzer/Godherja-Github-Version#236]
Hello! I was told to report this issue here by Rensebcrates on the discord. So, the Battle Magi Helm, as seen in this screenshot, or the other variant of it, no-longer appears in the Barbershop. This has been tested without any mods on by Rensebcrates.

Hope this helps! Please and thank you for reading and have a good day and night!
Side Note, i don't really know how github works, i just created an account to post this report, so if you reply or something and i don't see it, that is why. However you can contact me on the Godherja Discord, i'm Sulf#5092. Please and thank you for reading again, and have a good day and night, again!

![2022-05-17_24](https://user-images.githubusercontent.com/105762958/168944670-93400b6d-294e-438b-bf53-f451ba586444.png)
e

**Comment by ScionEol** [comment]
Already Fixed as of Patch 0.2.6.03
