### ISSUE TITLE
Bug Report: Can't recreate Opakhasia

### ISSUE THREAD

**Issue by ChadwickThunderstorm** [ThePinkPanzer/Godherja-Github-Version#238]
Hello, I'm submitting the save file for further investigation.

I've got three mods which shouldn't make a difference (Classic Map Modes, CFP, Interaction Icon Project) and you should be able to launch without them.

[Aautokratia_Eugenia_of_Bjaor_1298_06_05.pdf](https://github.com/ThePinkPanzer/Godherja-Github-Version/files/8738273/Aautokratia_Eugenia_of_Bjaor_1298_06_05.pdf)

Submitting as PDF, you can change it back to .ck3 right? Github is not OK with .ck3.

**Comment by ChadwickThunderstorm** [comment]
Oh come on

**Comment by Netgearghost** [comment]
We need pictures of the bug, and no that link won't work.
