### ISSUE TITLE
First three emperors of Chevalie lacks a culture (CULTURE BUG)

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#24]
The first three emeperors of Chevalie lacks culture and 2 of them lacks clothing because of it.
![image](https://user-images.githubusercontent.com/100115457/154902980-429d583a-a98c-45f6-985c-0a0856f06f08.png)
![image](https://user-images.githubusercontent.com/100115457/154903087-74f0e809-0edb-4e5c-bb58-62782d71ab50.png)

**Comment by Bommelom1** [comment]
This was a result of us forgetting to port the Shewigad culture over to the RC system, should be fixed in the next version now.
