### ISSUE TITLE
"Find Spouse" not available for children at game start

### ISSUE THREAD

**Issue by VenomJesus** [ThePinkPanzer/Godherja-Github-Version#243]
Exactly as the title implies. I can marry my children off to characters manually by arranging marriage with them, but there is no "find spouse" option available.

**Comment by Bommelom1** [comment]
Should be fixed for the next update (0.2.6.04). If you to quickly fix this yourself, the easiest way is to delete "can_do_diplomacy_trigger = yes" under is_shown in the marry_off_interaction in the 00_marriage_interactions file in common/character_interactions.
