### ISSUE TITLE
Infinite Load Bug

### ISSUE THREAD

**Issue by Chazem231** [ThePinkPanzer/Godherja-Github-Version#246]
Tried to load the mod twice, the first load I gave it 40 minutes and the second 15. I am stuck on Initializing Game.
https://media.discordapp.net/attachments/700521000772698152/986255973326934086/unknown.png?width=871&height=468
first load in discord.
![image](https://user-images.githubusercontent.com/52677806/173589095-17633de0-38a8-4cb3-b433-dd0eb8b58321.png)
Second load screenshot.

**Comment by Netgearghost** [comment]
Hopefully all infinite load bugs are fixed as of the latest version, if you still experience them please ping Netgear in the discord.
