### ISSUE TITLE
Wasteland recurited as court Dead Mage

### ISSUE THREAD

**Issue by stamau123** [ThePinkPanzer/Godherja-Github-Version#248]
![ftjfsd](https://user-images.githubusercontent.com/107490106/173606422-71e727f6-e200-4af3-ab52-2e069534a72d.PNG)
The decision to find court mage results in a human form of the wasteland becoming your court mage. This happened after choosing the most expensive search option.

**Comment by Bommelom1** [comment]
Should be fixed for the next version - when searching for a legendary magi it chooses the magi's culture (and religion) from a random county, and we forgot to add a check to prevent it from choosing a wasteland county.
