### ISSUE TITLE
NPC magic generation 

### ISSUE THREAD

**Issue by seethewinds** [ThePinkPanzer/Godherja-Github-Version#250]
NPCs are being generated with far too high magic potential at least up to magic_good_16

Lower level magi that are still powerful also generate too frequently such as the masterful magi and pure blooded levels. 

I don’t know what could be causing the issue but I’m reporting in presumption that it’s not intentional for there to be magi more powerful than aeschraes around.

**Comment by Bommelom1** [comment]
Are the ones with extremely high magic (16, 15 and 14) unlanded fogeaters named Natfraech, Dathal and Ualgarg? We accidentally gave some unlanded fogeaters waaaaay too high magic in the history files, so these ones are historical characters rather than characters being generated by the game.

**Comment by seethewinds** [comment]
Yes , however I have noticed NPCs also generate extraordinarily high. Many wasteland NPCs but also others. In my last game the mamur’s kid ended up as strong as aes. Many more pure blooded, exceptional, and masterful than before. That may be intentional. Before getting more magic blood than axiotheaos was very uncommon, now at least a dozen generate with it over time.
