### ISSUE TITLE
The Amsari Hiklahn has no succession law at game start

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#258]
![patata](https://user-images.githubusercontent.com/87128311/173863202-46304caa-0654-4369-ab94-bf8160f5fea6.jpg)
![patata](https://user-images.githubusercontent.com/87128311/173863453-6fe9e67b-ab1e-4fa7-8c1b-caa36662da55.jpg)

**Comment by Netgearghost** [comment]
Fixed
