### ISSUE TITLE
Missing loc for amsari_child_kill

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#259]
![patata](https://user-images.githubusercontent.com/87128311/173864210-7141cddf-81ae-4f27-97c4-1d3d7f03780d.jpg)
![patata](https://user-images.githubusercontent.com/87128311/173864619-c4eb9a6e-b29c-4511-9df4-bccf5737b312.jpg)
![Uploading patata.jpg…]()

No event or anything, the kid just dies of death_strangulation_killer. 
Also apparently the assassinated approves of her own assassination.

**Comment by Netgearghost** [comment]
Fixed
