### ISSUE TITLE
Amsari Reunification is bugged

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#261]
I won against all other contenders and nothing happened. I can't take the decision because I'm lacking "NOT_has_variable_trigger". 
![patata](https://user-images.githubusercontent.com/87128311/173932032-ff1f08ee-7d58-4b5b-bbd0-25215c6b373a.jpg)

**Comment by ThatOneGuy42** [comment]
fixed
