### ISSUE TITLE
Cannot Convert Culture

### ISSUE THREAD

**Issue by SRGKillz** [ThePinkPanzer/Godherja-Github-Version#263]
I cannot convert country culture as it says the action is unavailable even though I have already converted religion.
However, I notice by switching to a character that was not my start character I **can** convert culture.
It may be notable to say that the UI on the righthand side reverts to the vanilla UI when switching to a non-start character.

**Comment by lunelune2413** [comment]
Correction: It appears to be very random on who can and who can't. Some cultures CAN convert, some can't. Some big nations like the Imperrech can convert cultures, while the Khenemhat kingdom can't despite their culture being able to in the Shinaymah.

Some that can.
Chevalie:
![image](https://user-images.githubusercontent.com/100115457/174437203-2f2db640-f975-4e6d-8aa9-759170871218.png)
Vhanavid
![image](https://user-images.githubusercontent.com/100115457/174437130-a18fee7a-0ae2-43b0-8e65-6d075a77dff0.png)
Sjalvolki
![image](https://user-images.githubusercontent.com/100115457/174437143-99d8fcdd-7f68-408e-8856-26e3a9c9464b.png)

Some that can't:
All Aversarians:
![image](https://user-images.githubusercontent.com/100115457/174437290-26c8c090-de30-4010-9510-d9e2c87a99c4.png)
![image](https://user-images.githubusercontent.com/100115457/174437304-10561db2-5306-4ba8-ac52-cd705994698f.png)
Xajirkel:
![image](https://user-images.githubusercontent.com/100115457/174437341-6c9d0a95-88b0-4997-945d-8eb4c3453be3.png)
Suru'gin:
![image](https://user-images.githubusercontent.com/100115457/174437398-353ef7e1-a278-490c-b120-bba165b8293a.png)

**Comment by lunelune2413** [comment]
Make sure the culture you want to convert follows your religion. Only cultures who follow your religion can be converted :)
Found this out the hard way after a thorough 1 hour of testing various reasons on why this was the case. Until it just stumbled on me "Could it be like EU4 where they have to share you religion first?". Turns out, yes.
