### ISSUE TITLE
Multiple religions have missing head of faith duchy titles

### ISSUE THREAD

**Issue by Yimnoshant** [ThePinkPanzer/Godherja-Github-Version#267]
These include Uakaklo, Masaagnite, Stranuni, and every single Ritualist faith. (Not shown here)
![20220616100434_1](https://user-images.githubusercontent.com/107634243/174108953-ef0cf122-ce44-4435-9360-471c187d7b96.jpg)
![20220616100457_1](https://user-images.githubusercontent.com/107634243/174108987-6d1999a1-6912-4604-81fd-9b683ec4c99f.jpg)
![20220616100925_1](https://user-images.githubusercontent.com/107634243/174109021-6c91ece0-bdef-4251-b5b1-4e5b29f322c9.jpg)
)

**Comment by ScionEol** [comment]
Fixed in the next patch
