### ISSUE TITLE
Gender Law: The Sjalvolki Dovatkning

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#270]
Some countries (the Fenvir, at least) have The Sjalvolki Dovatkning as gender law, which for example means that Cormag Fenrus' player heir (and the person that will inherit his titles outside the capital) will be his elder daughter instead of his son.
![Godhe](https://user-images.githubusercontent.com/87128311/174323395-853c5b88-c1d3-4f53-9709-3a90cc3f9100.jpg)

**Comment by Netgearghost** [comment]
Fixed them being shown as gender laws
