### ISSUE TITLE
All Aversarians, including those in Krejehad, have the option to form Aversaria Voreias, which makes no sense

### ISSUE THREAD

**Issue by Yimnoshant** [ThePinkPanzer/Godherja-Github-Version#273]
![krejehad voreias](https://user-images.githubusercontent.com/107634243/174459919-5faf57da-4b11-4ebe-ab6b-7e10f04cc475.jpg)

**Comment by Netgearghost** [comment]
Fixed so its not restricted to the Black Sun in 1254
