### ISSUE TITLE
Marshland hunt encounter in the Foglands

### ISSUE THREAD

**Issue by Yimnoshant** [ThePinkPanzer/Godherja-Github-Version#274]
Got one of the hunt events while in the foglands, and met the most sane fogeater ever
![pictured-themostinsanefogeater](https://user-images.githubusercontent.com/107634243/174461167-e21ee798-040f-4848-b041-4d07493535cd.jpg)

**Comment by ThatOneGuy42** [comment]
fixed in next patch
