### ISSUE TITLE
Legendary Beastmaster REMOVES the ability to hunt high level monsters

### ISSUE THREAD

**Issue by TheOneNation** [ThePinkPanzer/Godherja-Github-Version#275]
I went up the monster hunter chain with the standard progression. When I was a 3rd level monster hunter, I could hunt the legendary beasts. Once I killed an abyssal monstrosity, though, it leveled me up to "Legendary Monster Hunter" -- and suddenly I wasn't able to hunt any of the stuff I was able to hunt at 3rd level. Please fix this, I love the hunting events!

**Comment by Bommelom1** [comment]
Should be fixed for the next version - also sent you a reply with the fixed file on Discord if you want to fix it yourself for this version.
