### ISSUE TITLE
Delinox son of The Black Sun cannot acrue magic. 

### ISSUE THREAD

**Issue by AlexiReynov** [ThePinkPanzer/Godherja-Github-Version#280]
Delinox does not acrue magic each month. On the second day of the game other characters who have both a school of magic and a Magi trait gain the icon for magic and begin to acrue. 

Despite having both Living mage II (0.3 per month) and Gifted Magi (1.5 per month) this does not happen for Delinox.

![Delinox](https://user-images.githubusercontent.com/107814521/174500016-a1d91030-1dc6-4071-a9f5-a32085d7c767.jpg)

Magic is not added when using study the arcane or Flagellate (despite wounds occuring as expected)

![Delinox 2](https://user-images.githubusercontent.com/107814521/174500235-2e35fec9-faa7-43b3-9317-bfcaed5a1e38.jpg)

Other characters who start the game unlanded do acrue magic, as do those who start landed. 

![Delinox 3](https://user-images.githubusercontent.com/107814521/174500570-7684e8a7-ebb3-482b-a49f-6061bbb238a8.jpg)

**Comment by Bommelom1** [comment]
Should be fixed in next version. If you want to give him proper access to magic in your current save, you'll need to use debug mode and type "effect add_to_magi_list = yes".
