### ISSUE TITLE
Court magi transfer magic task always transfers 0 magic (fix included)

### ISSUE THREAD

**Issue by d-n-f** [ThePinkPanzer/Godherja-Github-Version#293]
See e.g. this image another user posted in discord
![image](https://user-images.githubusercontent.com/26857757/175790641-c56993b3-be09-440e-a78b-1e53220e3421.png)

The reason this is happening is because the calculation of the script value `court_magi_transfer_value` depends on the variable `monthly_magic_no_transfer`, which gets cleaned up in the effect `remove_temporary_magic_calculation_variables_effect` for all AI characters, meaning its value is always 0 when it gets checked by the task.

If you change that cleanup effect to no longer invoke `remove_variable = monthly_magic_no_transfer`, then court magi transfer starts working again (well, give or take a year).

**Comment by Bommelom1** [comment]
Gotcha, should be fixed for the next version - pretty sure we accidentally removed it while trying to clean up variable bloat from magic calculations.
