### ISSUE TITLE
Anti-Magic Farmlands in Iyrossi Basin

### ISSUE THREAD

**Issue by Parori** [ThePinkPanzer/Godherja-Github-Version#3]
There is a misplaced Anti-Magic Farmlands in the capital barony of county of Skykanceoe
![2022_02_20_1](https://user-images.githubusercontent.com/12398081/154842378-fb54f4d4-84d4-4104-8033-bdd6e0a56bf6.png)

**Comment by ThePinkPanzer** [comment]
Fixed in 0.2.5.2
