### ISSUE TITLE
Hunt Event Chain Break

### ISSUE THREAD

**Issue by LaVonZer** [ThePinkPanzer/Godherja-Github-Version#30]
Sometimes hunting event chain wouldn't trigger. Looking at it through debug mode finds out several insight. Hunting a recently hunted creature, either successfully or not, result in event chain discontinued. Although it will be available again later, some traits that allows hunting more frequently would be trapped inside this chain break.
<img width="660" alt="GH hunt bug report" src="https://user-images.githubusercontent.com/100140023/154966967-d54baf87-3d5d-41d1-82f7-7e9dcf19926e.png">
Here a normal option which normal event chain should continue as intended,
<img width="660" alt="GH hunt bug report b" src="https://user-images.githubusercontent.com/100140023/154967166-b4b10773-2bda-4750-b94e-02712e00072e.png">
and here is the creature hunted before, choosing this option will result in event chain break.
Also, sometimes one rare creature would stalk your hunts, no matter where you go. Like, if you hunted a Werewolf once it will appear every time you hunt again even in different locations.

**Comment by FedorBozic** [comment]
Could you provide a save game where if you go on a hunt this happens, and tell me which specific biozone/creature is problematic? Also an error log file. This issue has been confounding me for some time and I cannot even consistently replicate it on my end.

EDIT: Nevermind, I've replicated it, found the cause and fixed it. Thank you for your report.

**Comment by LaVonZer** [comment]
You are welcome
