### ISSUE TITLE
Typo in province name "FlampiloX"

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#308]
The last letter of this province's name is a capital X. I doubt that was intended. It is owned by a Sjalvolki now because of the invasion, but I don't know if this is a Sjalvolki cultural name or the original name. It sounds more Aversarian, I think. 
![2022_06_29_3](https://user-images.githubusercontent.com/18605346/176546130-a0f8f4d7-41d6-4e29-a97d-00ad4a163fbd.png)

**Comment by Archduke476** [comment]
Fixed in next patch
