### ISSUE TITLE
Hunt Event Chain Result in Massive Weight Loss

### ISSUE THREAD

**Issue by LaVonZer** [ThePinkPanzer/Godherja-Github-Version#31]
Going for hunt for too long, not only result in event prompt firing each day, but also result in weight loss for companion characters. Maybe it was designed so that the player character would consider their action on hunt. As the player character will be given certain modifier, either hunger or hypothermia, which eventually expire. While the accompanying character would still be hungry, without any clear modifier, and in one other playthrough it would go down as much as -70! I don't exactly know if the target weight would rebound back but I don't think it is.
<img width="550" alt="GH hunt bug report hungy" src="https://user-images.githubusercontent.com/100140023/154968824-ec6aa8dc-c7a3-4aa2-baf3-9d3c794c04a0.png">
Here she have accompanied former hunt, which last for a month or so, and have her target weight reduced down to -30.

**Comment by FedorBozic** [comment]
I don't think that the weight loss is necessarily a result of the hunting expedition, more than likely it's a coincidence unless other people have also noticed something similar. On the other hand, which specific event prompt do you mean when saying "not only result in event prompt firing each day"? The one where you pick a tracker? Or the one where you track? Because the latter is intentional and how hunt tracking works.

**Comment by LaVonZer** [comment]
I will check the playthrough where several of my courtier got a lot skinnier.

and that "event prompt firing each day" is a joke about how hunting tracking event pops up daily, if that is how thing is intended then it is.

**Comment by LaVonZer** [comment]
There she is, the one with -70 target weight.
After a lengthy one month hunt, I just realized the peculiar variable, is this intentional? 
<img width="750" alt="GH hunt bug report hungy 2b2" src="https://user-images.githubusercontent.com/100140023/155251517-569d5337-22df-4954-a564-a8a57a5de865.png">
I cannot really imagine what -124 character weight would looked like.

**Comment by FedorBozic** [comment]
I'm not sure if it's intentional or where it's even coming from but that variable is definitely not emanating from hunt events.

**Comment by FedorBozic** [comment]
Correcting myself - it is indeed related to hunts, but mostly since vanilla hunts are spaced out by 5 years whereas ours are by 6 months in some cases. I'll balance the numbers a bit.

**Comment by LaVonZer** [comment]
Thank you very much
