### ISSUE TITLE
I can swear fealty to Cenware as Iordanes

### ISSUE THREAD

**Issue by SaffLemon** [ThePinkPanzer/Godherja-Github-Version#310]
I assume aversarians shouldnt be able to just swear fealty to Cenware, as it allows them to keep their entire realm unchanged

**Comment by ThatOneGuy42** [comment]
Iordanes can bc that is canonically what he does. As well, even swearing fealty will not protect you from the Migration, as Aagiokratians are explicitly blocked from receiving Kingdoms from the Imperrech Migration.
