### ISSUE TITLE
Aversarian faith bishops (landed and court) are naked

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#312]
Your court priest and count+ levelled bishops for the various Aagiokrata faiths are naked.
![image](https://user-images.githubusercontent.com/100115457/176644428-ba11c49d-3388-47cb-82df-12aa61d96759.png)
![image](https://user-images.githubusercontent.com/100115457/176644571-f65f2af7-0c01-4cec-afba-43ff2fbd88f8.png)
![image](https://user-images.githubusercontent.com/100115457/176645127-cbdfa549-004e-407d-b5c5-6d30c087fe0a.png)

**Comment by FedorBozic** [comment]
Fixed
