### ISSUE TITLE
Main Menu Blank after loading

### ISSUE THREAD

**Issue by BraveYoungJake** [ThePinkPanzer/Godherja-Github-Version#324]
Every time I load the game, the main menu will load, but nothing will be displayed that I can interact with. I can see my cursor, and interact with the checksum number in the lower right, but outside of that there is nothing. I've tried clicking around to possibly see if the menu items are there but simply not visible, but had no luck.

I've checked and can confirm I am using the correct version. I've tried uninstalling and re-installing both the mod and the base game. I've tried disabling the latest DLC, removed all other mods to just have this one the only one installed and running, I've tried in windowed mode and full screen, I've checked and confirmed that the base game loads correctly and the menus are visible. 

I'm out of ideas on what could be causing this.

<img width="1920" alt="blank menu" src="https://user-images.githubusercontent.com/49603200/177077485-dc5c95ce-1e37-4ce7-a38a-4f72c41d4aa3.PNG">

**Comment by ThatOneGuy42** [comment]
Would you be able to send your error.log file from this happening?

**Comment by BraveYoungJake** [comment]
I ended up deleting everything CK3 related from my computer, in addition to a re-install, and it finally fixed itself. Guessing it was a weird issue with settings and not specific to Godherja itself (though weird that it only occurred when trying to use the mod.)
