### ISSUE TITLE
Legendary Monster Slayer disables higher level hunts

### ISSUE THREAD

**Issue by F00tMaNatArMs** [ThePinkPanzer/Godherja-Github-Version#329]
![image](https://user-images.githubusercontent.com/103208921/178066925-6588a81e-1d30-4677-954e-d3e4222c4f54.png)
Seems permissions that are granted to level 3 Monster Slayer are not added to level 4 one

**Comment by Bommelom1** [comment]
Ugh, thought I'd fixed this already. Should be fixed for the next version - if you want to fix this yourself, go to the GH_adventure_hunt_triggers file in common/scripted_triggers and remove the "has_trait = beasthunter_3" on line 74.
