### ISSUE TITLE
Sjalvolki characters remaining naked after duel

### ISSUE THREAD

**Issue by TomHadas** [ThePinkPanzer/Godherja-Github-Version#33]
Hi,
Starting as Sigrun Axe-in-Hand, I noticed that several Sjalvolki character, including Sigrun herself and her son, remained half-nude after their first in game duel (from both random events and the succession).
When the duel started the characters changed to the semi-nude apparel they use for the fight, but after the duel's ending, they did not switch back to their previous attire, instead, their default appearance became the nude one:
![image](https://user-images.githubusercontent.com/100153819/155001054-2ccadce2-96e5-43f8-8cbb-78c8db61851b.png)

Changing their appearance manually with the barber works, but when switching back to the default option (for the dynamic appearance), it remains the nude version.

**Comment by lunelune2413** [comment]
Can confirm. This still happens.

**Comment by FedorBozic** [comment]
I am unable to replicate this in our latest dev build. I'm going to assume that it's fixed, and if not someone will presumably report it again and correct me.

**Comment by TomHadas** [comment]
Hi,
I believe I saw it mentioned as fixed in one of the last few patches, thanks!
