### ISSUE TITLE
Arayvtar "Other faith of Ahridar" infinite declare self Malaak

### ISSUE THREAD

**Issue by IdleZealot** [ThePinkPanzer/Godherja-Github-Version#330]
![MultipleDevouts](https://user-images.githubusercontent.com/108975961/178097946-9fe24054-2ebd-430b-8318-8282700f5cdf.png)
![DeclareUnlanded](https://user-images.githubusercontent.com/108975961/178098135-ed2b7ee5-fdb3-4f8d-8efe-2c75f5d2a61e.png)
![EventTriggered](https://user-images.githubusercontent.com/108975961/178098140-6f269c4d-00f3-4a50-a143-0194e7653ca9.png)

**Comment by FedorBozic** [comment]
Fixed
