### ISSUE TITLE
GUI Scaling

### ISSUE THREAD

**Issue by lurtze1** [ThePinkPanzer/Godherja-Github-Version#337]
Setting GUI scaling to 100% with these settings 
![image](https://user-images.githubusercontent.com/9928487/179612307-42aaf776-4d2c-4731-80f2-cacd2e233a82.png)
causes the main menu to look at follows
![image](https://user-images.githubusercontent.com/9928487/179612171-64c8b827-8cf0-4d00-8a35-0cd8a414bb45.png)

**Comment by Tywele** [comment]
#251 I posted a workaround here
