### ISSUE TITLE
Dethedklann Accord lacks proper localization

### ISSUE THREAD

**Issue by Xerodoeht** [ThePinkPanzer/Godherja-Github-Version#339]
![image](https://user-images.githubusercontent.com/36612871/180620358-829d79d8-2c51-47c2-8dc5-ae602c307260.png)
reproducable by converting to the religion and then looking at where it says your religion, it has an underscore instead of a space. This is also true on the map
![image](https://user-images.githubusercontent.com/36612871/180620393-cea2da67-d75c-499a-9d90-bfdc89da628a.png)

**Comment by Xerodoeht** [comment]
Also, the religion has the exact same color as portenchant, so they are impossible to distinguish from the religion map without clicking on it.

**Comment by Archduke476** [comment]
Fixed in next patch
