### ISSUE TITLE
Republican and Theocratic succession laws cannot be changed as a feudal lord

### ISSUE THREAD

**Issue by TomHadas** [ThePinkPanzer/Godherja-Github-Version#34]
Playing as a tribal or feudal lord, count and duke level titles (king and emperor were not tested) with theocratic or republican successions remained non-feudal after conquest or revocation, and could not be changed (the remove law button is grayed out):
![image](https://user-images.githubusercontent.com/100153819/155003197-c0fa3bef-f118-414d-9a9a-402984ab2d3f.png)

This remains even after switching the county or ducal capital to a castle:
![image](https://user-images.githubusercontent.com/100153819/155003305-3c8db324-b692-43a4-97b1-0dbd0969b6a1.png)

The only solution I found so far was to destroy and recrate the title, which incurs a lot of costs and penalties for ducal titles, and is impossible for counties.

(I assume playable theocracies and republics are related to this issue)

**Comment by Bommelom1** [comment]
Thought I'd made the laws disappear if held by a ruler of the wrong government, but turns out I forgot to implement that - should be fixed in the next version.
