### ISSUE TITLE
Designation of Heir is limited to Chevalien Legacy tradition; still not working.

### ISSUE THREAD

**Issue by Architekts** [ThePinkPanzer/Godherja-Github-Version#348]
When attempting to designate an heir, you have this prompt:

![image](https://user-images.githubusercontent.com/70243968/184783463-8721268f-fdde-42de-a209-85d4ee37bd5c.png)

Whether or not it's intentionally supposed to be like this, it still doesn't work even if you hybridize and add their tradition to your culture.

![image](https://user-images.githubusercontent.com/70243968/184783592-0200c0dd-dc1f-43bb-99ca-d4ae2ad70cba.png)

It could be that it's not actually a part of the Chevalien Legacy tradition to allow it? Not sure.

![image](https://user-images.githubusercontent.com/70243968/184783892-5d7fd08d-0f47-41fd-a3ce-4f45e9c5a0e5.png)

**Comment by ThatOneGuy42** [comment]
fixed
