### ISSUE TITLE
Hecaeda's invasion of Asiupoli bugged

### ISSUE THREAD

**Issue by TomHadas** [ThePinkPanzer/Godherja-Github-Version#35]
Going through the Olentic-alliance route for Hecaeda, it seems the CB for invading Fenvir is bugged:
When using the decision, both options (calling the Olentic tribes or not calling them) result in Hecaeda declaring a CB-less war, which invalidates a day later with no follow-up.
It seems to happen regardless of whether Fenrus is still ruling the clan.

![image](https://user-images.githubusercontent.com/100153819/155023477-6d0528ac-faf1-4258-83b4-f3892a5978a0.png)

**Comment by Netgearghost** [comment]
Appears to have been fixed by someone in a previous patch.
