### ISSUE TITLE
Missing Holy Sites for Iyrossi

### ISSUE THREAD

**Issue by VectusPrime** [ThePinkPanzer/Godherja-Github-Version#360]
Both the native Iyrossi faith and the Iyrossi Aagiokratia are missing holy sites
![20220915132031_1](https://user-images.githubusercontent.com/97322812/190510744-04bd15b9-b9e4-4b11-ad6b-55ae7a248892.jpg)
![20220915135919_1](https://user-images.githubusercontent.com/97322812/190510755-0aaa6357-97c0-487d-bf13-8cc336eaf66d.jpg)

**Comment by QuintusAquila** [comment]
I ran into the same bug and found the problem. It looks like when they deactivate the holy sites for the kardwen/apti, it deactivates them for every religion.
