### ISSUE TITLE
Book Merchant Bug

### ISSUE THREAD

**Issue by HansFlammenwerfer** [ThePinkPanzer/Godherja-Github-Version#365]
Book Merchant shows three books, but third option gives you the same book as the first.
![image](https://user-images.githubusercontent.com/113685005/190659815-9219997c-de2b-4bb7-9e62-353560c5f06c.png)
![image](https://user-images.githubusercontent.com/113685005/190659855-0ad7da91-5e73-42c5-b43f-14dae00ae111.png)

**Comment by FedorBozic** [comment]
Fixed
