### ISSUE TITLE
Main Menu Never Pops Up After Loading

### ISSUE THREAD

**Issue by honkel** [ThePinkPanzer/Godherja-Github-Version#367]
System specs: Ryzen 5900HS, 3070 mobile GPU, windows 11
Game loads as normal and then landing page hits, audio for main menu shows up and the menu never appears
[error.log](https://github.com/ThePinkPanzer/Godherja-Github-Version/files/9590840/error.log)
<img width="1280" alt="Screenshot_1" src="https://user-images.githubusercontent.com/1912674/190838760-bb4842ed-5078-4390-8137-d67b087301d0.png">
edit: wrong cpu

**Comment by honkel** [comment]
I have acquired someone else's error.log who also has this issue, may it shed light.
[error(1).log](https://github.com/ThePinkPanzer/Godherja-Github-Version/files/9591257/error.1.log)

**Comment by ThatOneGuy42** [comment]
Can you try loading the game without mods, going into your settings ingame & seeing if the gui size is not at 100, if it is not adjust to 100 & relaunch with mod?

**Comment by honkel** [comment]
@ 100%
<img width="1280" alt="Screenshot_2" src="https://user-images.githubusercontent.com/1912674/190877091-1316c001-c4ee-4545-b960-b6ba0c5a6c06.png">
@ 120%
<img width="1280" alt="Screenshot_3" src="https://user-images.githubusercontent.com/1912674/190877096-40f62d1d-6f17-4ced-a269-efc67233a3e0.png">
@ 140% (finally standard
<img width="1280" alt="Screenshot_4" src="https://user-images.githubusercontent.com/1912674/190877106-c33e246e-762d-4ae3-8d1c-186eceebc854.png">

All at 1440p

> Can you try loading the game without mods, going into your settings ingame & seeing if the gui size is not at 100, if it is not adjust to 100 & relaunch with mod?
