### ISSUE TITLE
Vargenis culture has wrong cultural description

### ISSUE THREAD

**Issue by Groofey** [ThePinkPanzer/Godherja-Github-Version#37]
Vargenis (the small culture west of the deresstae) have the cultural description of the Jakana. As can be seen in this image:
![image](https://user-images.githubusercontent.com/100166448/155028175-c050f7a6-e2e1-498a-b7f0-5116dadbf9ef.png)

**Comment by Netgearghost** [comment]
Appears to have been fixed in a previous patch.
