### ISSUE TITLE
Kikarsags and Vhanavids do not get their cultural titles

### ISSUE THREAD

**Issue by KingSpicy** [ThePinkPanzer/Godherja-Github-Version#381]
Checking the files it looks like they're in there but in game the only title that shows up is "Beiyan" on tribal Vhanavid duchies. At first I thought it was because vhanavid and kikarsag were possibly mispelled in gh_culture_titles_english.yml but changing the spelling broke the localisation for tribal vhanavid duchies. I've noticed this issue a few versions ago but I haven't seen anyone bring it up so I felt I should.

**Comment by KingSpicy** [comment]
Ok it looks like I fixed it by playing with the priorities in gh_title_holders.txt. I've included the modified file below.

[gh_title_holders.txt.txt](https://github.com/ThePinkPanzer/Godherja-Github-Version/files/9662305/gh_title_holders.txt.txt)

**Comment by FedorBozic** [comment]
Thank you for the fix, we implemented it.
