### ISSUE TITLE
"World" instead of "Word" is used in the description for Dgudi.

### ISSUE THREAD

**Issue by IustinusTempus** [ThePinkPanzer/Godherja-Github-Version#388]
![image](https://user-images.githubusercontent.com/30352026/193411528-a9744122-9973-408a-be6e-203f3e8760ff.png)

**Comment by FedorBozic** [comment]
Not a mistake.

**Comment by IustinusTempus** [comment]
Could you explain why exactly? I'm reading it over and over again but I'm pretty sure it is supposed to be "word."

**Comment by FedorBozic** [comment]
The Great Spirits created the world, as in they created Aeras/the Universe. They didn't create the grammatical concept of what a word is.
