### ISSUE TITLE
Can't build Manor Houses

### ISSUE THREAD

**Issue by Parori** [ThePinkPanzer/Godherja-Github-Version#4]
Unlike in normal Farmlands terrain, you can't build Manor Houses building line in holdings on Anti-Magic Farmlands terrain
![2022_02_20_4](https://user-images.githubusercontent.com/12398081/154842731-6d52e89f-5ba7-4c77-af6e-1c21bafa3db1.png)
![2022_02_20_3](https://user-images.githubusercontent.com/12398081/154842739-359e1ed6-510f-47ff-9305-e7bf537411a1.png)

**Comment by ThePinkPanzer** [comment]
In future please don't forget to label bugs

**Comment by ThePinkPanzer** [comment]
Fixed in 0.2.5.2
