### ISSUE TITLE
Canian traditions don't match their lore

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#40]
![gode2](https://user-images.githubusercontent.com/87128311/155038707-97fa040b-72c4-451c-b1f1-79bbad1bfb97.png)
![gode2](https://user-images.githubusercontent.com/87128311/155038744-fa59547c-13a0-44e2-b39d-d3342bf16890.png)

**Comment by Archduke476** [comment]
Hopefully this should fit better for now
