### ISSUE TITLE
Wardenite faith - Classism = Egalitarian should let me designate heir, but I can't desginate heir

### ISSUE THREAD

**Issue by smackdabinthemiddle** [ThePinkPanzer/Godherja-Github-Version#402]
I adopted Maridai'A, which should let me designate heir. I cannot designate heir:
![image](https://user-images.githubusercontent.com/53697571/194363242-71d682c4-1144-4270-a9c8-791bbe150ab1.png)

**Comment by FedorBozic** [comment]
Fixed
