### ISSUE TITLE
Can somebody pls explain to me what i am doing wrong

### ISSUE THREAD

**Issue by googs90** [ThePinkPanzer/Godherja-Github-Version#404]
![Screenshot (3)](https://user-images.githubusercontent.com/115419517/194769439-8c2ea6a9-1924-4d72-ad30-0beac94c9c25.png)

I have the newest version of the Mod via steamworkshop and all dlcs.No other mods , latest update of ck3.

Thanks for the help

**Comment by Yimnoshant** [comment]
It might be because your language for CK3 is set as German, which the mod doesn't have translations for. There's a Godherja German Translation mod on the Steam Workshop, but it hasn't been updated for 2 years, so it probably won't work.

Hope this helps.

**Comment by googs90** [comment]
Your suggestion was the answer to my problem,thank you.
