### ISSUE TITLE
Sjalvolki Dovatkning as the High King of Chevalie

### ISSUE THREAD

**Issue by HegemonRene** [ThePinkPanzer/Godherja-Github-Version#412]
![Screenshot (434)](https://user-images.githubusercontent.com/116698527/197923543-00424778-23df-47e8-90e7-01d227e4408b.png)
High King died and I guess the game thought I was Sjalvolki and gave me the "Challenge claimants to the throne" event. I wanted to see what would happen if I chose the bottom option and it basically ended my game as I lost everything

**Comment by ThatOneGuy42** [comment]
resolved for now
