### ISSUE TITLE
Assissinations don't fire sometimes

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#43]
Sometimes I've noticed that despite being at 95% and the event fires, assissinations don't seem to actually go through. It's just stuck at 95% and you get the choice to start a new one.

**Comment by Rawilson03** [comment]
That's the exact same issue I've found. It's rather annoying when I can't murder the people I want to

**Comment by Owl9999** [comment]
I've also had this happen once

**Comment by FedorBozic** [comment]
We think we finally solved this on our end. If it rears its head again after the next patch do tell us though. If it is any consolation, it was trying to fire a murder save event that has been removed from vanilla in the interim, so your plot would've failed anyway.
