### ISSUE TITLE
Hathahi'a name in the religious screen is wonky

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#436]
This has probably already been reported multiple times. Just wanna make sure it's not forgotten about :)
![image](https://user-images.githubusercontent.com/100115457/208425780-1c0c8a7c-2102-42df-95a0-07e5d2150b2b.png)

**Comment by NameAlreadyTakenCK** [comment]
I think that it is also issue with the holdings :) Generally this diactric (like others) behaves somewhat wonky.
![image](https://user-images.githubusercontent.com/121045832/208470606-2f1551d5-f9aa-4978-9c3a-eead260ac386.png)
