### ISSUE TITLE
Capitals of Krehejad and Epavarion/Niiadinia seem to be under the map

### ISSUE THREAD

**Issue by Austincantswim** [ThePinkPanzer/Godherja-Github-Version#439]
![20221219080127_1](https://user-images.githubusercontent.com/105401497/208467119-6dadae8a-1a1d-4265-ac7c-7589a1bf0c41.jpg)
![20221219103344_1](https://user-images.githubusercontent.com/105401497/208467137-08660133-6395-4832-aabd-98c4ff681174.jpg)

**Comment by lunelune2413** [comment]
Can confirm this is the case.

**Comment by Austincantswim** [comment]
![20221220125335_1](https://user-images.githubusercontent.com/105401497/208734444-024a654c-df5c-4f90-85bb-23f8a10c46c0.jpg)
![20221220125446_1](https://user-images.githubusercontent.com/105401497/208734453-d2ee1a93-b192-4abb-ba52-961ec97b84d5.jpg)
Also noted the Ayyar and Harthath's capital are under the map.
