### ISSUE TITLE
Bug?: Garneix Deivonex and the impossible alliance. 

### ISSUE THREAD

**Issue by Rawilson03** [ThePinkPanzer/Godherja-Github-Version#47]
The Changelog made mention of a powerful alliance between Garneix and Wirikind Slativiaka, however in the game this alliance doesn't exist and bar the massive difficulties to convert to Sjalvoki as an Aversarian reformed faith would be impossible due to either figures mutual hatred of one another.

**Comment by ThePinkPanzer** [comment]
Does the alliance outright not trigger or is it just that the AI will never accept a DOW?
