### ISSUE TITLE
Holy Orders changing to feudal after creating a custom character

### ISSUE THREAD

**Issue by KrystofKalvach** [ThePinkPanzer/Godherja-Github-Version#49]
So I wanted to play as the Order of the Forlorn Guardian while creating a custom character and the Landed Holy Order changed to Feudal after I started the game

**Comment by Bommelom1** [comment]
This was happening due to any custom character with a castle capital automatically being made Feudal, next version should have traits in the Ruler Designer for changing the government of your custom character.
