### ISSUE TITLE
Northern Rite War Ending Decision Bug

### ISSUE THREAD

**Issue by travislibre** [ThePinkPanzer/Godherja-Github-Version#493]
![Screenshot (188)](https://user-images.githubusercontent.com/97703722/217968000-8e715ca1-ae29-4688-92b4-eb5e218433bb.png)
"The Struggle Phase is Hostility Phase" requirement doesn't seem to trigger despite being in the Hostility phase of the Northern Rite Wars.

**Comment by ThatOneGuy42** [comment]
You have to be Involved in the Struggle, it's checking both the phase & your involvement, you are currently an Interloper
