### ISSUE TITLE
Bug Report-Creating new faith crashes game

### ISSUE THREAD

**Issue by Owl9999** [ThePinkPanzer/Godherja-Github-Version#50]
I was playing a save game as the Partics, and wanted to create a new faith. The game crashed immediately after finishing the whole process. Oddly enough, the "death" sound affect that you hear when you get the notification that your ruler has perished accompanied the crash. I was using a few other steam workshop mods, but even after disabling all of them, the problem persisted. Even someone else who had entirely different mods said that it happened to them as well, so I doubt that is the issue.

**Comment by FedorBozic** [comment]
Did you make sure you picked an icon for said faith?

**Comment by Owl9999** [comment]
> Did you make sure you picked an icon for said faith?

Well this is embarrassing.. I could have sworn I did, but I suppose not. Thank you for the help, and sorry for the inconvenience
