### ISSUE TITLE
Vrodkin character creating generic divergent culture despite Sjalvolki having 28 custom ones

### ISSUE THREAD

**Issue by FatLeek** [ThePinkPanzer/Godherja-Github-Version#504]
![Zrzut ekranu (238)](https://user-images.githubusercontent.com/101152217/224851968-b5a151e9-9d31-437d-82cd-d5d47973196b.png)

She named it after her county.

**Comment by Lewa263** [comment]
And now she will be an interloper in the Rite Wars struggles.
