### ISSUE TITLE
The "Break my Strings" decision for Cois isn't working

### ISSUE THREAD

**Issue by MrRinn** [ThePinkPanzer/Godherja-Github-Version#529]
I've met the requirement of the Conclave faction having less than 200% power and been notified that it's available, but clicking on it doesn't do anything to Cois, or trigger any events, or even take the decision off the major decisions list, I've clicked it repeatedly with the same result.

**Comment by FedorBozic** [comment]
Decision has been removed in the latest dev build since it no longer serves any purpose.
