### ISSUE TITLE
Sourthern Kemsar baronies and counties are teleporting all over the place (Probably caused my left over straits)

### ISSUE THREAD

**Issue by lunelune2413** [ThePinkPanzer/Godherja-Github-Version#530]
I think this alongside the Mayikrata needs to be looked into for the hotfix

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/d583d314-9e35-49f6-a0cc-0d48c965e9d6)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/2d47b28f-591f-4605-b32a-4cac2e44e461)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/1a759f36-0ecf-47c2-bba0-7f2afae1ac83)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/a5647c74-31b2-4cc6-8009-1b398fccf2fa)

**Comment by lunelune2413** [comment]
There's simply too many of them to list

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/07dcfa1e-91c7-4279-8402-a7f6f44b3100)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/5df70084-7dd1-4e81-a178-06c1a9f1f227)

**Comment by lunelune2413** [comment]
Also a small missing loc found:
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/100115457/ebd6c0dd-fb7f-455c-9379-e4d5355d2a2a)

**Comment by ThatOneGuy42** [comment]
Fixed
