### ISSUE TITLE
Prince of Fashion Nickname Localization Error

### ISSUE THREAD

**Issue by Mikk348q** [ThePinkPanzer/Godherja-Github-Version#540]
![20231028142611_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149245933/a69539f9-76da-4f55-9128-6cd15f5b78cb)
During the "[Child]'s First Enrobing" event, one of the options for the event gives your child the nickname "The Prince of Fashion".
However, due to (presumably) a bug of some kind, the nickname instead appears as "Nick_prince_of_fashion".

Whether this applies to a female counterpart to the title or not, I do not know.
EDIT: It applies regardless of gender.

**Comment by lunelune2413** [comment]
Saw this as well

**Comment by FedorBozic** [comment]
Fixed.
