### ISSUE TITLE
Forming the Mountain-Sun Concordat to end the Southern Rite wars, doesn't give the dynasty renown

### ISSUE THREAD

**Issue by MaxxxEC** [ThePinkPanzer/Godherja-Github-Version#548]
Just did it in my game, no renown gained. No mods besides Godherja.

**Comment by MaxxxEC** [comment]
Looking in the decisions file for the Rite Wars, I don't even see why it doesn't, looks proper.

**Comment by Bommelom1** [comment]
It was because "dynasty = { add_dynasty_prestige = 3000 }" was only in a "show_as_tooltip_effect", meaning you don't actually gain any renown.
Should be fixed for the next version.
