### ISSUE TITLE
Educated magi without magi congenital trait

### ISSUE THREAD

**Issue by Ferzenant** [ThePinkPanzer/Godherja-Github-Version#550]
Some characters get magi education not been actually magi. Looks like bug. Latest Godherja version.
![Безымянный](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149278032/d7679cfe-7d63-45ce-9b69-4a213c70561f)

**Comment by ThatOneGuy42** [comment]
Not a bug, you're not required to have the traits to be a Magi
