### ISSUE TITLE
Magical Prowess does not exist outside of start of game value

### ISSUE THREAD

**Issue by vtmt2000** [ThePinkPanzer/Godherja-Github-Version#554]
what it says in the title if you generate a new magi with the "search for a magi" decision they won't have magical prowess, if you have magical children and wait for them to grow up they won't have magical prowess, if you take the "focused casting" Arcana perk the amount of magical prowess won't change from the one you had at game start.

**Comment by knightmare-ui** [comment]
I have had the same issue, not running any other mods. I have also noticed the issue happen to character creation characters as well. Their magical congenital trait prowess does not add to the overall combat prowess
