### ISSUE TITLE
Barbershop crash based on 'Godherja Headgear'

### ISSUE THREAD

**Issue by jpchdiaz** [ThePinkPanzer/Godherja-Github-Version#556]
Around year 1338 in a Ironman Rene 'The Black Bastard' start. 

Decided to play around in Barbershop around this year. I kept going back and forth to 'edit' a character (and then back to the Scene tab to proceed with pictures) and both times I've experienced this CTD was when trying to click the dropdown for 'Godherja Headgear' when going back to the edit appearance screen. The dropdown wouldn't appear in this case; just freeze for a second and instant-CTD.

I can't seem to reproduce it 100% of the time; I'd actually say -most- times so far, this dropdown works, opens and changes headgear just fine.

As a related sidenote, it looks like 'Godherja Headgear' is just out of the way for men and can't be scrolled down to.
![20231030131134_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/30698143/83e2d049-4c2e-49c0-822c-c8648b1cf06a)

![20231030131116_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/30698143/756868a1-fc3d-4073-8f9a-022a46524359)

**Comment by ThatOneGuy42** [comment]
Should hopefully be resolved in Hotfix 3 but please report if it happens again
