### ISSUE TITLE
Amaghean Tower and other related towers have bugged Extended Magic Baseline effects

### ISSUE THREAD

**Issue by trueeranam** [ThePinkPanzer/Godherja-Github-Version#558]
The Amaghean Tower, the Eastern, Oltenic and Desert Towers only yield 1 point of Extended Magic Baseline.

![Bug](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149421871/7a37dc33-f9ff-4cc7-bd1d-fa803d441847)

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
