### ISSUE TITLE
Oltenic is considered Astray by Sjalvolki Faiths

### ISSUE THREAD

**Issue by Xerodoeht** [ThePinkPanzer/Godherja-Github-Version#56]
![image](https://user-images.githubusercontent.com/36612871/155779766-6c860960-f731-4457-ae4f-6bdadce6b84f.png)

Should be visible by just clicking a sjalvolki character and going to the oltenic faith, it is the same for the sjalvolki reformations too.

**Comment by Xerodoeht** [comment]
All of the oltenic sub-faiths are as well

**Comment by FedorBozic** [comment]
Fixed
