### ISSUE TITLE
Alkaba Alalmadi Special Building in the Tall Iskaya providing only +1 Extended Baseline instead of the stated +100

### ISSUE THREAD

**Issue by MaxxxEC** [ThePinkPanzer/Godherja-Github-Version#580]
https://imgur.com/a/Yayn1us

**Comment by MaxxxEC** [comment]
https://imgur.com/a/uhUBING
The bloodcrystal mine in Epaverion as well

**Comment by MaxxxEC** [comment]
I'm also finding it at all of the Towers, which it looks like other people have reported already

**Comment by trueeranam** [comment]
Basically every single building adding Extended Baseline are bugged
