### ISSUE TITLE
City mayor AI doesn't upgrade Guilds building

### ISSUE THREAD

**Issue by HoboWithaSh0tgun** [ThePinkPanzer/Godherja-Github-Version#583]
All DLCs, no additional mods. Main mod resubbed, files restored, PC restared.
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149743160/57464443-bddc-4951-b6b2-afd6d9de64ee)

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149743160/873731a1-fc3d-4086-a1b3-7651c27889b1)

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149743160/2811a81e-5d6d-4bf6-9169-a8781f377cb2)

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149743160/6e2e1ca3-abc8-4f3c-9d96-3b641309fc05)

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
