### ISSUE TITLE
Scripted character still has outdated Dead Magic Adept trait

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#595]
Abbad Muhaddad (char id tasurmad_wardenism_85), the youngest brother of Mamur Adabyn, still has the Dead Magic Adept trait left over from the old magic system. He does not have any magic in the current magic system.

![2023_11_08_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/e8899007-9201-419f-ada9-d3c4d31e5d24)

**Comment by MaxxxEC** [comment]
Fixed, have given him school of manifestations
