### ISSUE TITLE
Hubarite Codices Bug

### ISSUE THREAD

**Issue by Pr1smane** [ThePinkPanzer/Godherja-Github-Version#606]
After the start of the game, after a month has ticked over - the historical characters associated with the Hubarite codices seem to disappear from the game. 
![ghbug2](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/151188489/5fb2afc5-4fc4-4af4-84ef-912d9e40ff96)
![ghbug1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/151188489/808a1753-241f-4182-9c17-a118388e6d27)

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
