### ISSUE TITLE
Foreign Affairs Task Doesn't Work

### ISSUE THREAD

**Issue by Pr1smane** [ThePinkPanzer/Godherja-Github-Version#613]
The foreign affairs task does not provide any scaling prestige - no matter the skill of the chancellor. It seems to provide a consistent and flat 1.00 prestige per month. The prestige shown on the task tooltip is always 0.

![ghbug4](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/151188489/a4425788-cbf0-4384-8851-7af74bcbfcc5)
![ghbug3](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/151188489/bb82ad8b-1cba-4566-a9db-c5a89c6934e2)

**Comment by Bommelom1** [comment]
Can't seem to replicate this in the current dev version, so I'm closing it as fixed.
