### ISSUE TITLE
Cannot Remove Deceased Magic Targets

### ISSUE THREAD

**Issue by travislibre** [ThePinkPanzer/Godherja-Github-Version#615]
It's currently impossible to de-select dead magic targets, as the right-click won't allow you to interact with them. Could possibly be solved by adding an additional button to de-select all targets.
![Screenshot (200)](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/97703722/00ea9920-4bc3-419a-ab0c-7cb87417b5cc)

**Comment by Bommelom1** [comment]
Can't actually seem to replicate this - characters should be automatically removed from magic lists when they die, and when I tested this it appeared to be working.
We're still adding a self-targeting character interaction to clear your magic list in the next version just in case, though.
