### ISSUE TITLE
Marmaladid cultures start with war elephants but not war camels

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#616]
The Marmaladid cultures are mostly in the deserts of Sarradon, where they probably would benefit more from camels than elephants. Yet in the culture history file, they are given the innovation for elephants in 1250 (see first screenshot) and need to research camels. I suggested changing this years ago (see second screenshot), but dgl said to make a bug report.

![Screenshot 2023-11-24 215026](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/41a184cd-9e0c-4ea3-a910-21d42af5ba03)

![Screenshot 2023-11-24 214832](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/272dfd6c-59a7-4289-97aa-f99d22cb4b1f)

**Comment by FedorBozic** [comment]
Fixed.
