### ISSUE TITLE
Can't invite non-guest courtiers or fund inspirations anymore

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#617]
Since the 0.3.0.8 patch to GH, I can neither invite non-guests to my court nor fund inspirations in my court. The tooltips do not explain why. When I turn off debug mode, they just have "All of these:" in red with nothing below. This happened when I played Cormag Fenrus last night and now it's the same for Mamur Adabyn. My best guess is that something was changed with the triggers that both of these use, in which case there are likely other interactions that are also currently impossible.

![2023_11_26_2](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/2e6b5825-e7be-4fbd-a612-56c85d81e503)

![2023_11_26_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/912b1331-3cb2-4ecd-9e11-fbfc5e386de1)

**Comment by KotyaLevski** [comment]
Same
