### ISSUE TITLE
the metro building discount from the Centralized culture tradition is not working

### ISSUE THREAD

**Issue by AFlamingCat** [ThePinkPanzer/Godherja-Github-Version#618]
<img width="1280" alt="2023-12-02 (1)" src="https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149910460/11da5130-9996-4e45-9899-a735a3c3fc2c">
<img width="1280" alt="2023-12-02" src="https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149910460/efe65246-2c42-463a-98e9-708eec6ff8f6">

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
