### ISSUE TITLE
Bug reformation aversarina aagiokrata

### ISSUE THREAD

**Issue by Heractos44** [ThePinkPanzer/Godherja-Github-Version#619]
![Bug godherja](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/152694552/8b5fea7e-e7a5-4c35-bf12-f459412bbb3b)

So I get this message when I reformed the Aversarina Aagiokrata

**Comment by Bommelom1** [comment]
References to the dummy tenet should be fixed (hidden) in the next version.
