### ISSUE TITLE
Partic Holy Order is bugged and units maybe wrong too

### ISSUE THREAD

**Issue by Runnerstun** [ThePinkPanzer/Godherja-Github-Version#62]
![Screenshot_154](https://user-images.githubusercontent.com/100493636/155860163-4226c7ee-ed11-475d-9a48-4680b2375eca.png)

**Comment by Killmatronix** [comment]
https://i.imgur.com/ceyAQpA.png
https://i.imgur.com/ShFlxDY.png
Mine has Magi but still no name.

**Comment by Netgearghost** [comment]
fixed
