### ISSUE TITLE
Haruspicy isn't working correctly

### ISSUE THREAD

**Issue by AFlamingCat** [ThePinkPanzer/Godherja-Github-Version#620]
It has a mismatch between what it says you get and what you actually get and you only get one stack even if you should have multiple.
<img width="1280" alt="2023-12-03 (4)" src="https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149910460/d22974ef-ab2e-40c7-8a4d-da94a32ab624">

<img width="1280" alt="2023-12-03 (5)" src="https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149910460/25e0b29a-baf5-43ac-8b4b-f5896dfc2fe4">
<img width="1280" alt="2023-12-03 (6)" src="https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/149910460/3306e30a-8255-474f-8cc3-425c44dbe932">

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
