### ISSUE TITLE
Aironian Agiokrata religion continuously revokes temples from priests and gives to ruler.

### ISSUE THREAD

**Issue by Zangunaz** [ThePinkPanzer/Godherja-Github-Version#622]
First noticed when playing as Legan Hecaeda, you start with a temple and whenever that temple is then assigned to someone as a vassal, within a few days that vassal will become landless and the temple given back to you. This does not occur on other religions, even on the same character.

Converting back to Aironian Agiokrata immediately gives all temples in your domain to you. Not playing with any other mods.
[Bug_save1.zip](https://github.com/ThePinkPanzer/Godherja-Github-Version/files/13573704/Bug_save1.zip)

**Comment by ThatOneGuy42** [comment]
fixed in next patch
