### ISSUE TITLE
Black-Gold League Standard court artifact is invisible

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#627]
The Black-Gold League Standard is a large wall ornament court artifact that starts with Ansfrei in Marroux. It doesn't show up in the court when displayed. In my screenshot, it is in the back left corner, as you cannot see.

![2023_12_19_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/18605346/7ab810bd-e137-4fce-9e6e-4295a95232dd)

**Comment by ThatOneGuy42** [comment]
resolved
