### ISSUE TITLE
Minbiri'a event can fire multiple times for same character

### ISSUE THREAD

**Issue by Lewa263** [ThePinkPanzer/Godherja-Github-Version#628]
The event where a Wardenite's child falls in with Minbiri'a radicals (event id `wardenite_yearly_0011`) can fire multiple times for the same character, because the character flag that it checks for in the trigger block (`had_event_wardenite_yearly_0011`) is not actually applied by the event firing. I've been playing Mamur Adabyn for only 3 years in my current save and have had this event twice for the same son.

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
