### ISSUE TITLE
Aversarians converting to Orasipolj

### ISSUE THREAD

**Issue by LoganLogan0** [ThePinkPanzer/Godherja-Github-Version#632]
![2023_12_24_13](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/61169830/9d1ee8d4-90be-4e3a-973d-d946a1e731f7)

Manic Aversarian vassal conquered praznarva province, immediately met with a billion events to convert to Oraisopolj rite (which she did).

Assume this is a bug as it makes about 0 sense

**Comment by LoganLogan0** [comment]
As a followup, it seems to happen to anyone who touches a unreformed sjalvolki province, marchers, agionists....

**Comment by ThatOneGuy42** [comment]
should be handled though please report again if it persists
