### ISSUE TITLE
Cannot use "Learn Magic School" Scheme despite satisfying all requirement

### ISSUE THREAD

**Issue by jeffwzhu** [ThePinkPanzer/Godherja-Github-Version#633]
# Description:
As a Magi, I am currently unable to Learn a new school of magic despite having the 'Sage' perk from the Arcana Lifestyle Tree.
I have tried both premade and existing characters, and characters with an existing school of magic + characters without any prior school.

# Steps to reproduce:
Pick a character with a Magi trait or create a new Magi character. Give yourself the Sage perk using console commands or unlock it organically. Try using the "Learn Magic School" scheme on another Magi character, and you won't be able to.
With debug mode on, you'll also be able to see an error: "Current level cannot be automatically flattened Use custom_tooltip or custom_description" -- though I have no idea if this actually relates to not being able to learn a new school of magic.

# Screenshots:
Here's what it looks like:
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/13359007/90a97739-887f-4802-95b8-6a620716ccf1)

In debug mode:
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/13359007/89381d89-41c8-4538-9081-6eda0d3820aa)

**Comment by Bommelom1** [comment]
Huh.
So, the problem is that some of the current requirements for leaning a school of magic are apparently not shown - the target must have a reason for being your teacher, such as being your friend, family member, spouse, courtier or court mage.

**Comment by Bommelom1** [comment]
All unmet requirements for the "Learn Magic School" and the "Learn Magic Spell" scheme interactions should be shown correctly in the next update.
