### ISSUE TITLE
Missing Loc(?) for Barony B_Crumblegate in the County Underclans in Duchy of Murkwood

### ISSUE THREAD

**Issue by Novallus** [ThePinkPanzer/Godherja-Github-Version#635]
I didn't realize that we could report these until I saw a message about it in the discord, so I'll probably report more as I find them.

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/153843251/b7051096-979b-44fd-a492-bf4a4af188b5)

**Comment by ThatOneGuy42** [comment]
handled
