### ISSUE TITLE
Game crashes when putting up decoration while playing specific ruler

### ISSUE THREAD

**Issue by MiaMax445** [ThePinkPanzer/Godherja-Github-Version#641]
So when playing Grand Duke Casimir IV of Ziemojycz, I’ve found that whenever you put on the dynasty/house banners in your royal court, the game ends up crashing. I have no other mods enabled and I checked with other nations and they don’t have the same problem.

Thanks,

mia

**Comment by PericlesAO** [comment]
I'm having the same problem.  It appears to be the Ojzaca banner that is causing the crash.  Usually you get two banners for your house with the same name but different quality and stats, but these two banners seem to imply they belong to different houses.

**Comment by ThatOneGuy42** [comment]
Will be fixed in the next patch
