### ISSUE TITLE
Several Minor Province Issues (Opakhasia)

### ISSUE THREAD

**Issue by Rouental** [ThePinkPanzer/Godherja-Github-Version#651]
In Opakhasia, there are a few minor issues with the provinces that I noticed. 

1. In the County of Knidike, Mantussae and Antocaea are both Necropolises.
2. In the County of Lamathon there's something funky with the location of Reselis, which causes troops marching to it to end up in a completely different spot from the on screen barony. Likewise, trying to march to either barony in the County of Golgembria results in your armies doing loops all over the place.

**Comment by ThatOneGuy42** [comment]
resolved
