### ISSUE TITLE
Various UI bugs

### ISSUE THREAD

**Issue by DyonisXX** [ThePinkPanzer/Godherja-Github-Version#655]
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157083263/7bf99feb-0fd5-4c6d-b9b4-63dc0457eb10)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157083263/a6d3b10f-08b4-4e09-b0eb-d3c42941052a)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157083263/ba5c81d8-10d7-4b32-a2d4-b5c7c720729a)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157083263/45b7c7ff-79dd-4540-8655-5fda2df45e42)
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157083263/5c1ec731-cefa-4742-912f-3bf0ff642df6)

**Comment by DyonisXX** [comment]
1. Text
2. Ambient Magic hidden behind the other window
3. Unclickable Alliance flag outside the window
4. 6th building slot outside the window
5. Text

**Comment by ThatOneGuy42** [comment]
Resolved in next update
