### ISSUE TITLE
Minor problems in Malcois 

### ISSUE THREAD

**Issue by Rouental** [ThePinkPanzer/Godherja-Github-Version#656]
When playing in Malcois, I noticed a few minor things.

1. In the County of Meletiosdothex, the barony of Gennadiossoa seems to lack localization or something, as it appears as "b_gennadiossoa"
2. There's something wrong with Posike, when I try to march troops into Astaleth, their movement arrows goes halfway across the map into Rim'da. Likewise, when I try to move troops into the barony of Haeios in Posike, they end up on Nanatoat's Discovered in Maratrnoplofon.

**Comment by Rouental** [comment]
Another problem similar to #2 was located in the County of Gissegnes, in the barony of Pathaceve, where trying to move in it results in your army appearing in Imevemo.

**Comment by ThatOneGuy42** [comment]
Resolved in next update
