### ISSUE TITLE
A holy site is listed for a faith that does not exist

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#66]
![image](https://user-images.githubusercontent.com/86840465/155933621-6a5bf41c-27a9-4fbe-a949-2258026e6d86.png)
`westcatacombs_12bb` is not corroborated elsewhere in the code, not as a county nor in the holy sites code file.

**Comment by Netgearghost** [comment]
Added in the holy site for Aeulikai religion
