### ISSUE TITLE
Lich rejection characters that are human + in my realm as a vassal are not able to be demanded to change their religion and obtain pretty powerful stats

### ISSUE THREAD

**Issue by nachtmaerie** [ThePinkPanzer/Godherja-Github-Version#663]
Don't get me wrong, it's pretty funny, but having a lich culture-faith character in your realm is probably not intended haha.

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/157994436/a3963444-434f-4f36-bee7-0617f105daae)

**Comment by ThatOneGuy42** [comment]
Resolved in next update
