### ISSUE TITLE
One ending of Northern Rite Wars struggle seems to be bugged

### ISSUE THREAD

**Issue by szynutix-sz** [ThePinkPanzer/Godherja-Github-Version#668]
![Screenshot from 2024-02-08 23-53-12](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/159494865/1c2e3487-edf3-4ba6-b71c-c45e922a9f0e)
It should have checked of the box with the current phase being hostility. Also should i be able to do it with just holding these five counties? I got a sense that I should need to conquer most of the territory between them.

[Link](https://github.com/szynutix-sz/CK3-saves/tree/main/Godherja/2024_02_09) to the save, meta.yml and pdx-settings.txt

**Comment by ThatOneGuy42** [comment]
You are an Interloper, not Involved, in the struggle, and the decision trigger checks based on involvement.
