### ISSUE TITLE
Mending spell seems to do nothing.

### ISSUE THREAD

**Issue by szynutix-sz** [ThePinkPanzer/Godherja-Github-Version#669]
![mending_problem](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/159494865/58bdd8a8-cb98-4526-ab96-e0129eb36e58)

After casting it also does not seem to do anything.

[Link](https://github.com/szynutix-sz/CK3-saves/tree/main/Godherja/2024_02_09) to the save, meta.yml and pdx-settings.txt

**Comment by FedorBozic** [comment]
Fixed.
