### ISSUE TITLE
Badari'a icon missing

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#67]
![image](https://user-images.githubusercontent.com/86840465/155950760-cba59842-d9a9-4d90-ba09-038b0ee288c6.png)
![image](https://user-images.githubusercontent.com/86840465/155950842-1cb5f1f9-0fe3-45ac-a49c-6e6a0b5b5923.png)
`badari_icon` is not corroborated by a dds image in the mod files.

**Comment by Archduke476** [comment]
Fixed and pushed
