### ISSUE TITLE
Rejuvenating Blood spell says it would apply four stacks of Rejuvenating Troops but gives only one.

### ISSUE THREAD

**Issue by szynutix-sz** [ThePinkPanzer/Godherja-Github-Version#673]
[Link](https://github.com/szynutix-sz/CK3-saves/tree/main/Godherja/2024_02_09/Screenshots) to the screenshots
They are called rejuvenating_blood_problems 1 and 2

**Comment by ThatOneGuy42** [comment]
Resolved in next update
