### ISSUE TITLE
men at arms UI for Stats

### ISSUE THREAD

**Issue by ThatCatWh0** [ThePinkPanzer/Godherja-Github-Version#674]
An issue with men at arms UI not displaying stats

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/121317462/42294116-1c27-4463-b58c-c810cd4bed5b)

**Comment by ThatCatWh0** [comment]
Update for this issue, as the issue is tied to Godherja: Addon for Aversaria Submod

**Comment by FedorBozic** [comment]
Since this is something from a submod (that's not managed by us), it will not be fixed.
