### ISSUE TITLE
Restoring Etepezea bug

### ISSUE THREAD

**Issue by JkdudeZ** [ThePinkPanzer/Godherja-Github-Version#675]
after restoring etepezea, the game starts lagging heavily and spamming into the error file

```
[19:08:20][jomini_script_system.cpp:276]: Script system error! (while building tooltip/description)
  Error: untyped trigger [ Scoped object of type 'landed_title' is not valid (null weak (Landed_titleВ вЂ” 4294967295)!) ]
  Script location: file: common/scripted_effects; restore_traditional_borders line: 11
 file: common/decisions/gh_cultural_major_decisions_aversarian.txt line: 907
 file: common/scripted_effects; restore_traditional_aversarian_borders_etepezea line: 3
```

**Comment by ElvenLiberation** [comment]
I also experienced this bug and I believe the lag might have something to do with that it somehow added 504 wasteland placeholder characters to the de jure of the new empire of Etepezea - if you have an elective succession law like Aristocratic Elective you can see your elector count shoot up by 504. Removing the elective succession before restoring fixes the problem.
