### ISSUE TITLE
"Establish an Aristoracy Through The Rite" decision is visible for non sjalvolki characters.

### ISSUE THREAD

**Issue by spartanyanni** [ThePinkPanzer/Godherja-Github-Version#676]
As a shattered islander chief (Calystoanistism, Guillater), the decision for quickly changing goverment to Aristocratic that seems to be meant for Sjalvoki characters as the rites emerge is visible for me, despite not being of a Sjalvolki culture or religion.

![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/3102450/934c82af-57f0-43e3-9c08-1b952ce7d030)

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
