### ISSUE TITLE
Veloscoup Event Third Option Bug

### ISSUE THREAD

**Issue by Snowduck23** [ThePinkPanzer/Godherja-Github-Version#677]
The Veloscoup Event keeps popping back up every time I press the third option to remain with the Orispoji Rite.

https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/160694013/7b2ec4db-e741-4390-b160-b66b4b685b43

**Comment by ThatOneGuy42** [comment]
Resolved in 0.3.1 (next update)
