### ISSUE TITLE
Magocracy has to be updated to work with the new magic traits

### ISSUE THREAD

**Issue by FeanorTheElf** [ThePinkPanzer/Godherja-Github-Version#678]
I have finally managed to reform my government to Magocracy, but my inheritance is bugged. My primary heir is always disinherited on succession by the magocracy script, despite he/she being a powerful mage. I looked into the game files, and the script checks for a flag can_access_magic on any of the traits, but this flag is only set for the "old" Living/Dead/Mixed magic traits (education_living_magic_1 etc).

Also, the decision to reform the government to Magocracy checks that all your Vassals are Magi depending on their Blood, Stone & Ethereal aspect score, this should probably either use the same flag as above, or at least check all possible magic aspects...

# The relevant sections of the game files:

In `gh_magocracy_effects.txt`:
```
        every_close_family_member = {
		limit = {
			can_access_magic_including_children = no
		}
		add_trait = gh_temporarily_disinherited
		trigger_event = {
			id = magocracy.0002
			days = 2
		}
	}
```
In `gh_magic_triggers.txt`:
```
can_access_magic_including_children = {
	has_trait_with_flag = enables_magic
	NOT = { has_trait_with_flag = can_not_access_magic }
}
```
In `03_GH_magic_traits.txt`:
```
education_living_magic_1 = {
	monthly_arcana_lifestyle_xp_gain_mult = 0.1
	flag = character_extended_magic_baseline_add
	flag = blood_spellcasting_add
	flag = fire_spellcasting_add
	flag = enables_magic
	shown_in_ruler_designer = no

        ...
```
and so on.

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
