### ISSUE TITLE
Harthah ibn Sarradon Starting War Invalid

### ISSUE THREAD

**Issue by Kaferian** [ThePinkPanzer/Godherja-Github-Version#68]
![20220228172327_1](https://user-images.githubusercontent.com/100638010/156069067-a6cfced2-31fe-451d-88b4-281b561c51b9.jpg)
![20220228172335_1](https://user-images.githubusercontent.com/100638010/156069068-64f044cd-813f-43bf-94f3-2ad8629c7a22.jpg)
![20220228172155_1](https://user-images.githubusercontent.com/100638010/156069070-b4795c4e-ce08-410e-ba72-404e3dc176ad.jpg)
This is likely the same issue that's occurring with Hecaeda's reconquest war.

**Comment by UltimateVictory** [comment]
This bug has been fixed on the dev end, closing issue.
