### ISSUE TITLE
Choosing Ojyczaynz Lick culture in ruler creation, makes me unable to have men at arms 

### ISSUE THREAD

**Issue by ArxFatalis23** [ThePinkPanzer/Godherja-Github-Version#684]
Whenever I try to choose the Ojyczaynz Lick culture, I'm unable to have or recruit men at arms regiments.

**Comment by ThatOneGuy42** [comment]
This is intended behavior. You should not be selecting the Lich culture for a normal game (and I likely need to block normal conversion or access altogether to prevent this), but as the Undead they do not use MAA or normal buildings nor normal innovations.

**Comment by ArxFatalis23** [comment]
Well, if you could please tell me, how do I play as Lich culture? Or where I could find out somehow.
