### ISSUE TITLE
Extended magic baseline bonus from waylines doesn't work

### ISSUE THREAD

**Issue by Hyborem** [ThePinkPanzer/Godherja-Github-Version#686]
Magic interface shows you the bonus, but after uncapping magic generation and trying to actually reach this extended threshold, you can notice that you, in fact, can't do it. For example, starting as Tetradia in 0.3.0.11, with a capital in an ordinary wayline province, your extended baseline should go up to 250 (as it is shown in the interface), but after uncapping magic generation, it only goes up to 200. If you take Places of Power perk, your extended magic baseline is still effectively capped at 200.

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
