### ISSUE TITLE
Missing loc for `saratan_religion` both name and desc.

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#69]
![image](https://user-images.githubusercontent.com/86840465/156076824-ad420025-e0f7-4f9e-a4ff-03689f9bd16f.png)
![image](https://user-images.githubusercontent.com/86840465/156076890-2cc9173f-3a7a-482b-932e-1acdbecdaded.png)
`saratan_religion` is not corroborated in the loc files.

**Comment by litten8** [comment]
fixed
