### ISSUE TITLE
Redlander Murder Issues

### ISSUE THREAD

**Issue by Acrepe** [ThePinkPanzer/Godherja-Github-Version#695]
Currently, the Redlander god demand where they must murder a set number of people only counts murders where the victim has the "murdered" cause of death. This means that murders that do not apply this cause of death (IE most of them), and which for example have the cause of death listed as "suspicious circumstances", do not count towards the murders committed.

**Comment by ThatOneGuy42** [comment]
Adjusted to account for different murder possibilities
