### ISSUE TITLE
Arthenax Holy Site is in wrong location

### ISSUE THREAD

**Issue by H1eronymous** [ThePinkPanzer/Godherja-Github-Version#697]
holy site in Sicerma county
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/25139845/30fa2ea9-d754-4cf0-93eb-6d1080785301)
Dragon Bones in Solstice county
![image](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/25139845/a575707f-79c2-47fc-84c2-0e4ad186e25b)

**Comment by ThatOneGuy42** [comment]
fixed
