### ISSUE TITLE
Impossible to access the castle of Kamera

### ISSUE THREAD

**Issue by zeltron1** [ThePinkPanzer/Godherja-Github-Version#699]
Clicking on the castle has you select the temple of Beos

![Screenshot 2024-07-09 162310](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/174716755/fd6e246a-b75a-478e-8bf8-2bbc7d9e0091)

![Screenshot 2024-07-09 162323](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/174716755/22bbef2d-1b1d-45d2-8b78-b8d6827268bb)

**Comment by ThatOneGuy42** [comment]
fixed
