### ISSUE TITLE
Loc errors in Aesthetics descriptions

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#7]
![gode2](https://user-images.githubusercontent.com/87128311/154854250-d1189aeb-4d2b-4aea-9211-477631c8bf4e.png)
![gode2](https://user-images.githubusercontent.com/87128311/154854262-3b71d398-6b5b-492a-8443-f4eff9594ff8.png)

**Comment by ThePinkPanzer** [comment]
Fixed in 0.2.5.2
