### ISSUE TITLE
Rejection religion's description is cut off

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#70]
The religion description for the Rejection religion (the lich religion) is cut off:
![image](https://user-images.githubusercontent.com/86840465/156082693-ce006563-8494-43e6-860a-c14f84c69dfb.png)
![image](https://user-images.githubusercontent.com/86840465/156082723-a4612a24-c98d-480f-94ea-0985a3361c10.png)

**Comment by forkis** [comment]
Sentence finished, pushed loc changes.
