### ISSUE TITLE
"Invite sjavolki defectors" decision for cois spawns the units in lichdoms.

### ISSUE THREAD

**Issue by SomeDudeOnTheInternetTheSecond** [ThePinkPanzer/Godherja-Github-Version#702]
![20240710223836_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/107616088/c1a6f4f7-9f75-4b49-acf9-fbb0e692fab5)
While having a Cois campaign i suddenly got lich ambushed, it seems that the "Invite sjavolki defectors" decision spawned them in lich lands, and their stay there triggered an ambush.
Checked in with debug mode and indeed, they spawn not in imperrech as they (i presume) should, but in Laodilene.
![20240710230817_1](https://github.com/ThePinkPanzer/Godherja-Github-Version/assets/107616088/3356814a-3dcf-4ba4-8c06-552fbc759be4)

**Comment by ThatOneGuy42** [comment]
fixed
