### ISSUE TITLE
Redlander issues with new uptade

### ISSUE THREAD

**Issue by OzanTheExa** [ThePinkPanzer/Godherja-Github-Version#704]
1-) Court physician position is not visible in court positions screen, assigning one via events or from the current situations tab immediately unassigns them. Might be intented?

2-) You can't hold tourneys and feasts as redlanders. Might be intented?

3-) Send child to pit interaction is broken as it shows a big red "Target is your courtier" warning, implying target needs to not be your courtier while being a courtier is also shown as a requirement.

4-) Kill orders from void gods don't work whatsoever. Also they don't run out of time, instead remaining time value goes below zero.

**Comment by ThatOneGuy42** [comment]
Should be fixed in upcoming hotfix, tourneys and feasts are indeed not valid for redlanders.
