### ISSUE TITLE
Oltenisn religion should probably be `Oltenism`

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#71]
![image](https://user-images.githubusercontent.com/86840465/156083469-c5ad70ed-bce4-4210-b9df-c80d84f1a0bd.png)
![image](https://user-images.githubusercontent.com/86840465/156083630-5c213547-d2aa-4e47-931e-636d70601028.png)
An assumption on my part but the religion name looks like a typo of Oltenism.

**Comment by litten8** [comment]
fixed
