### ISSUE TITLE
Can cast any spell from a culture's magic tab w/o knowing the spell

### ISSUE THREAD

**Issue by andews184** [ThePinkPanzer/Godherja-Github-Version#712]
As the title suggests all you have to do to cast any spell is select one from a culture tab, and then well that's it, you can cast the spell normally as if you were selecting it from your own spell list.

![Screenshot (13)](https://github.com/user-attachments/assets/990e0d11-e524-4700-800a-7122f14b1174)

![Screenshot (14)](https://github.com/user-attachments/assets/9b1f6bcf-aa04-4c44-b8b4-06adaac329f9)

![Screenshot (15)](https://github.com/user-attachments/assets/1903fc62-f2f8-4031-9c26-de09532a60f3)

**Comment by Bommelom1** [comment]
Being able to cast spells you do not know should be fixed for the next version
