### ISSUE TITLE
Claim Marcher Throne NOT_CHARACTER_ARE_IS_INCAPABLE unlocalized

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#715]
The claim the Marcher Throne decision requirements has NOT_CHARACTER_ARE_IS_INCAPABLE unlocalized.
![image](https://github.com/user-attachments/assets/cc67957b-7522-4092-9e2e-5fc149025e63)

**Comment by ThatOneGuy42** [comment]
fixed
