### ISSUE TITLE
When restoring Otached's Empire, titles in Aironoi are not integrated.

### ISSUE THREAD

**Issue by IMPULS3D** [ThePinkPanzer/Godherja-Github-Version#716]
Was playing as an Oltenic, and clicked the restore Otached's Empire decision. All Empire titles I had were destroyed. All empire titles in Kashirya were integrated into the Otached's Empire title, but titles in Aironoi were simply destroyed and not integrated.

**Comment by ThatOneGuy42** [comment]
adjusted somewhat
