### ISSUE TITLE
Starvayrd religion has no description

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#72]
![image](https://user-images.githubusercontent.com/86840465/156086753-b6de18c7-6467-43df-96a5-a04b4221d2b9.png)
![image](https://user-images.githubusercontent.com/86840465/156086818-e0a532f5-2f7e-4ba2-9f04-ff6b4f625082.png)
`starvayrd_religion` object has no `starvayrd_religion_desc` loc corroboration.

**Comment by ReciterofPoetry** [comment]
Ditto for `hulawite_religion`.
![image](https://user-images.githubusercontent.com/86840465/156087134-ddc973c7-ef67-4e8f-bffc-c0a7174ba5eb.png)
![image](https://user-images.githubusercontent.com/86840465/156087149-7dc3aac6-466b-43bb-a171-943bc6f534df.png)

**Comment by Netgearghost** [comment]
Loc implemented
