### ISSUE TITLE
Wrong placement of Harthah event troops

### ISSUE THREAD

**Issue by Haffnaff** [ThePinkPanzer/Godherja-Github-Version#720]
The 'Against the Agionists' event at the start of Harthah's campaign (event id: harthah_war.0100) is bugged. Taking the 'All of Sarradon marches with me!' option spawns his event troops WAY up in the Northeast of the Imperrech in the province of Lehsirob (provid 3318) where they are basically stuck until they starve to death.

Pic attached. 
![20240715210002_1](https://github.com/user-attachments/assets/9ce40bd4-e418-42bd-9f30-136a3ab87839)

**Comment by Bommelom1** [comment]
Should be fixed for the next version
