### ISSUE TITLE
Fogeater lichdom in the isles at game start

### ISSUE THREAD

**Issue by AFlamingCat** [ThePinkPanzer/Godherja-Github-Version#726]
![Uploading 2024-07-14 (2).png…]()

**Comment by AFlamingCat** [comment]
<img width="1280" alt="2024-07-14 (2)" src="https://github.com/user-attachments/assets/e0f0af74-b385-49fe-8c15-f99c4cfd919b">

**Comment by ThatOneGuy42** [comment]
Fixed next patch
