### ISSUE TITLE
Wasteland Ruler in event 

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#732]
Wasteland ruler appearing in a event. 
![image](https://github.com/user-attachments/assets/41a3d1c0-688f-4f6a-8169-4cabb3558a1d)

**Comment by Lordmitch2** [comment]
![image](https://github.com/user-attachments/assets/9cec458b-0e4d-4dae-ac10-27c3c9abf610)

**Comment by ThatOneGuy42** [comment]
Fixed in next patch
