### ISSUE TITLE
Can Designate Heir without Absolute Crown Authority 

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#733]
I can designate an heir with only High Crown Authority but it should require Absolute Crown Authority. The Designate Heir option can be chosen on any Crown Authority level. 
![image](https://github.com/user-attachments/assets/bdf3eaf8-c2f4-4dfe-a72b-b0cf56732fe1)

**Comment by ThatOneGuy42** [comment]
The High King of Chevalie is allowed the ability to designate heirs without Absolute Crown Authority.
