### ISSUE TITLE
Chevalie collapse errors

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#737]
When you have a weak heir for Chevalie but only one child or the other children sit out the war, you will still go through the events of starting the collapse but nothing happens and the High Kingdom of Chevalie title don't get destroyed.  
![image](https://github.com/user-attachments/assets/ab0ad99a-6102-4ab1-916f-ee9e52ad300b)
When you have a weak heir and chose to sit out the war but there is only one other participant, the High Kingdom of Chevalie title don't get destroyed and you get to keep the title. 
![image](https://github.com/user-attachments/assets/61f953a5-e62a-4011-b629-8fdf867233b7)

**Comment by ThatOneGuy42** [comment]
should be fixed next patch
