### ISSUE TITLE
The `ancient_religion` religion lists concubinage doctrine twice and is missing a marriage doctrine.

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#74]
![image](https://user-images.githubusercontent.com/86840465/156140187-d762ae52-74c7-41bb-93fa-e7ab33c23fd4.png)
In the code for `ancient_religion` it seems like instead of listing how many spouses a character can have, the religion has a duplicate of the doctrine that sets how many concubines a character can have.

**Comment by litten8** [comment]
fixed
