### ISSUE TITLE
Allied Through Marriage double same line

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#741]
There a repeated line, that is the same. It does not happen for all of them. 
![image](https://github.com/user-attachments/assets/d9cfa801-65e5-425c-b418-4dcb7751fe30)
![image](https://github.com/user-attachments/assets/95c84fc8-0655-4e06-9db5-32ac1bbf7885)
Here is an example of where it doesn't happen.
![image](https://github.com/user-attachments/assets/b9b37f17-b4c8-451e-940d-0fbc63a77e0b)

**Comment by Bommelom1** [comment]
This is an issue in vanilla as well

**Comment by Bommelom1** [comment]
Closing this as it seems to be a vanilla issue.
