### ISSUE TITLE
START_SCHEME_LEARN_MAGIC_SCHOOL and [magic_school|E] loc

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#743]
Missing loc for START_SCHEME_LEARN_MAGIC_SCHOOL and [magic_school|E] 
![image](https://github.com/user-attachments/assets/f4e99c99-e5d8-400c-a238-7f534ceef61b)

**Comment by Bommelom1** [comment]
Should be fixed for the next version
