### ISSUE TITLE
Redland Modifiers comma at the end

### ISSUE THREAD

**Issue by Lordmitch2** [ThePinkPanzer/Godherja-Github-Version#745]
Two Redlands Modifiers have a comma at the end of there descriptions. 
![image](https://github.com/user-attachments/assets/8321a93e-158e-455e-b581-074a980d159f)
![image](https://github.com/user-attachments/assets/99765119-0aee-4903-8cb1-bba074e8b966)

**Comment by Lordmitch2** [comment]
I wrote comma, I meant Quotation mark.

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
