### ISSUE TITLE
bug wasteland county in the shattered isles

### ISSUE THREAD

**Issue by JamesIanM** [ThePinkPanzer/Godherja-Github-Version#753]
County Oothan Diorg is a wasteland 

![image](https://github.com/user-attachments/assets/4674c2eb-71ae-48cb-b39d-8a290c71448f).

it usually granted to a  fogeater upon the game unpausing.

![image](https://github.com/user-attachments/assets/cb8ba108-b152-4aa8-9eb0-f668fdbc7a14)

it cannot be Colonize.

**Comment by Bommelom1** [comment]
Fixed the county being held by a fogeater for the next version
