### ISSUE TITLE
Necromantic Vitality - Strengthened Health doesn't stack 

### ISSUE THREAD

**Issue by Mestrehunter** [ThePinkPanzer/Godherja-Github-Version#758]
I should get Strengthened Health(2) as a permanent bonus but I only get Strengthened Health(1) 

![necromantic1](https://github.com/user-attachments/assets/a192d1b0-1c46-4380-8c7d-5d2152c117fc)
![necromantic2](https://github.com/user-attachments/assets/d9a053d6-12be-4b1f-9dc5-8a0b07b345f7)
![necromantic3](https://github.com/user-attachments/assets/f5fd2ca5-6865-4833-a0db-41d1fe19b1af)

If I cast the same spell again at lvl 6, the Strengthened Health permanent bonus doesn't stack yet the penalty does.
![image](https://github.com/user-attachments/assets/5686017d-4e25-4f81-a66f-4dca9901b914)

**Comment by Bommelom1** [comment]
There's no bug here - the duration of modifiers are listed below the modifier, not above.
So in the first casting, you do have 2 permanent modifiers - they're the two last modifiers, which do not have any duration below them.

**Comment by Bommelom1** [comment]
Anyways, closing this as there's no bug here - though I don't blame anybody for thinking there is, how the modifiers are listed is highly unintuitive.
