### ISSUE TITLE
No Lifepath traits for Wyrd Path followers

### ISSUE THREAD

**Issue by RubedoFox** [ThePinkPanzer/Godherja-Github-Version#759]
Characters with the Wyrd Path faith do not get any options for choosing a Way upon reaching adulthood or converting.

The Wyrd Path faith is not included under the initialize_valid_lifepaths_for_faiths effect in gh_lifepath_effects, adding it there seems to fix this problem.

**Comment by Bommelom1** [comment]
Should be fixed for the next version
