### ISSUE TITLE
The Ethylisiac holy site of Wintgard isn't shown at Wintgard and instead links to the Ethylisiac holy site of Gorlowa

### ISSUE THREAD

**Issue by Killmatronix** [ThePinkPanzer/Godherja-Github-Version#76]
https://i.imgur.com/CvqDjVL.jpg
Screenshot shows it as Wintgard, but that is the holy site of Gorlowa.

https://i.imgur.com/Aklt034.png
Wintgard in the center. Not showing as a holy site.

https://i.imgur.com/Dz5TcUl.png
Both holy sites showing the same barony.

**Comment by Netgearghost** [comment]
Changed over to the correct barony location
