### ISSUE TITLE
Learn Magic School scheme is greyed out even when selecting court magi

### ISSUE THREAD

**Issue by trueeranam** [ThePinkPanzer/Godherja-Github-Version#761]
No tooltip explains why the scheme is unavailable

![image](https://github.com/user-attachments/assets/c5fb6558-7e7c-4e12-8fc4-c1604dfddb7b)

**Comment by Bommelom1** [comment]
Tooltip should be fixed for the next version - currently, you need the Sage trait (from the Erudition Arcana Lifestyle Tree) to learn a seccond magic school.

**Comment by trueeranam** [comment]
Noted, thanks :) !
