### ISSUE TITLE
Tradeport Buildings Exist Beyond Coasts

### ISSUE THREAD

**Issue by Raeyvne** [ThePinkPanzer/Godherja-Github-Version#762]
So it looks like tradeports can be built anywhere for some reason. at the very least they are being built in provinces that make no sense to have them. 
![Screenshot_2](https://github.com/user-attachments/assets/fff1a8ba-95b2-4961-851d-611009223fa5)
![Screenshot_3](https://github.com/user-attachments/assets/49930397-b702-4037-a4b6-82d99c993cbd)
![Screenshot_4](https://github.com/user-attachments/assets/f5d8afca-93ee-4bdd-ad0b-a1a11af79a26)

**Comment by Bommelom1** [comment]
Should be fixed for the next version.
