### ISSUE TITLE
Harthah's wars are bugged

### ISSUE THREAD

**Issue by PabloCLL** [ThePinkPanzer/Godherja-Github-Version#8]
![gode2](https://user-images.githubusercontent.com/87128311/154857237-805afb72-d010-415a-a388-afc3c9a86721.png)
![gode2](https://user-images.githubusercontent.com/87128311/154857261-d7c67efb-0c9c-4133-866d-dbaca1619e7a.png)
![gode2](https://user-images.githubusercontent.com/87128311/154857293-3d03dda9-3fe4-47b6-b0a8-8d421b9d8369.png)
![gode2](https://user-images.githubusercontent.com/87128311/154857322-873aecb8-dad2-4119-a726-a6259403ed99.png)

**Comment by ThePinkPanzer** [comment]
Fixed in 0.2.5.2
