### ISSUE TITLE
Custom Characters Turn Military Orders Into Feudal

### ISSUE THREAD

**Issue by Cirkasius** [ThePinkPanzer/Godherja-Github-Version#80]
![20220302002229_1](https://user-images.githubusercontent.com/100110550/156300610-f4baeede-9a94-4974-aed4-9318873e3226.jpg)
Created a custom character as Legio Exodian which is a military order. However, when I clicked finished on my character it turned the gov into feudal.

**Comment by Bommelom1** [comment]
Next version should have ruler designer traits that allow you to choose the government of custom characters
