### ISSUE TITLE
Wrong Eastern Tower holy site for Vindeonian

### ISSUE THREAD

**Issue by LilyKaiserreich** [ThePinkPanzer/Godherja-Github-Version#81]
I assume this is a bug at least, but it seems the Vindeonian holy site for the Eastern Tower isn't located in the same county as the special building for the tower.
The image shows in red where the holy site is located and in yellow where the special building is located.
![Screenshot 2022-03-02 103051](https://user-images.githubusercontent.com/59504512/156334564-7a150e2c-9518-4c11-8aae-9afa4b216968.png)

**Comment by Netgearghost** [comment]
Fixed
