### ISSUE TITLE
Military district main holding borked

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#88]
![image](https://user-images.githubusercontent.com/86840465/156497819-14334f8a-677b-4ef3-98b8-3e93e67e5d3a.png)
![image](https://user-images.githubusercontent.com/86840465/156497845-718100c3-82ff-4abb-adbb-8eba891c1256.png)
Since the second and further levels of the main building are not designated as such they just show up as regular buildings in the El Qulatha capital of the Mamuramat/Sihnamiyah.

Also the localisation of the additional levels are missing.

**Comment by FedorBozic** [comment]
Fixed
