### ISSUE TITLE
Kargagos has a capital in the foglands

### ISSUE THREAD

**Issue by Xerodoeht** [ThePinkPanzer/Godherja-Github-Version#95]
![image](https://user-images.githubusercontent.com/36612871/157595570-fac9f782-386b-47ac-b2e7-a095e720bc7c.png)
the capital barony of the county of Kargagos, has one of its baronies in the foglands mistakenly
![image](https://user-images.githubusercontent.com/36612871/157595653-cb7540fd-9cbf-44c2-8930-67ad33ef5d2e.png)

**Comment by Netgearghost** [comment]
Fixed in a previous version
