### ISSUE TITLE
`A Triumph in Mukhtab` decision is borked , at least for later generations.

### ISSUE THREAD

**Issue by ReciterofPoetry** [ThePinkPanzer/Godherja-Github-Version#96]
Playing as the great-granddaughter of Adabyn, many times removed, and `A Triumph in Mukhtab` does not spawn any event. Furthermore, it can be repeatedly spammed for 500 prestige infinitely without going away.
![image](https://user-images.githubusercontent.com/86840465/158046758-6cdbeed4-6048-4ba6-818d-7f3d49ea2756.png)
![image](https://user-images.githubusercontent.com/86840465/158046745-467e0a57-c160-4f91-a644-9350a651b913.png)
This seems to be because while the _decision_ shows up even after 1360.1.1, no effects are coded in for it after that point, besides the immediate prestige gain: 
![image](https://user-images.githubusercontent.com/86840465/158046822-831363b7-6108-4e63-b75e-80de3e22a6b0.png)

**Comment by ReciterofPoetry** [comment]
Also, typo in the `Rule the Ayyar Directly` code:
![image](https://user-images.githubusercontent.com/86840465/158069346-b7feb2af-68f9-4239-805d-7bdfc73fcdfc.png)
`has_variable = demanded_ayyar_submissionn` should be `has_variable = demanded_ayyar_submission`.

**Comment by Netgearghost** [comment]
Fixed so these decisions can only be taken once now
