### ISSUE TITLE
4 Kemsari Tribes + Kathunian culture seems to be missing any innovation.

### ISSUE THREAD

**Issue by nah34** [ThePinkPanzer/Godherja-Github-Version#97]
![20220314024905_1](https://user-images.githubusercontent.com/101521284/158072537-494323ae-03dd-4f1d-8a6d-dc0e465ee075.jpg)
 
All four Kemsari Tribes on the far west seems to have 0 innovation, which, if not intended, I expect is just missing.

In addition, the count of Samayake who is Kathunian also has 0 innovation. He has only 1 county, and maybe it's left out for future updates regarding Kathun-Kai, but I thought it's better to mention it.

By the way, there were so many cultures in the mod, and I admire the dev team for polishing rest of the religions and cultures. It was gorgeous!

**Comment by Netgearghost** [comment]
Thank you for your kind words.
However the innovations is intentional for now
