### ISSUE TITLE
"There must be more, keep searching" option during hunts doesn't add up death chances properly

### ISSUE THREAD

**Issue by Killmatronix** [ThePinkPanzer/Godherja-Github-Version#98]
https://i.imgur.com/T4MnWhu.png

Had to do it a couple of times because I wasn't able to hunt any of the monsters. Percentage doesn't change when death starts being an option.

**Comment by FedorBozic** [comment]
There is no bug here, it's just the tooltip being slightly confusing. The % chances for hypothermia, hunger and death are completely independent of each other - it is entirely possible to have all three happen, or none at all, or any combination of them. The % is the chance of the individual thing being a part of the ultimate event outcome, not the _sole_ outcome.
